from enum import StrEnum


class SupplierStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    BLOCKED = "BLOCKED"
    INACTIVE = "INACTIVE"


class RequisitionStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PARTIALLY_SOURCED = "PARTIALLY_SOURCED"
    FULLY_SOURCED = "FULLY_SOURCED"
    CANCELLED = "CANCELLED"


class RequisitionPriority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    URGENT = "URGENT"


class RfqStatus(StrEnum):
    DRAFT = "DRAFT"
    ISSUED = "ISSUED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    AWARDED = "AWARDED"


class QuotationStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_EVALUATION = "UNDER_EVALUATION"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"


class PurchaseOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    ISSUED = "ISSUED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    FULLY_RECEIVED = "FULLY_RECEIVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class PurchaseOrderLineStatus(StrEnum):
    OPEN = "OPEN"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    FULLY_RECEIVED = "FULLY_RECEIVED"
    CANCELLED = "CANCELLED"


class GoodsReceiptStatus(StrEnum):
    DRAFT = "DRAFT"
    RECEIVED = "RECEIVED"
    UNDER_INSPECTION = "UNDER_INSPECTION"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_ACCEPTED = "PARTIALLY_ACCEPTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class GoodsReceiptLineStatus(StrEnum):
    RECEIVED = "RECEIVED"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_ACCEPTED = "PARTIALLY_ACCEPTED"
    REJECTED = "REJECTED"


class InspectionStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    PENDING = "PENDING"
    PASSED = "PASSED"
    PARTIALLY_PASSED = "PARTIALLY_PASSED"
    FAILED = "FAILED"


class InvoiceMatchStatus(StrEnum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    WITHIN_TOLERANCE = "WITHIN_TOLERANCE"
    EXCEPTION = "EXCEPTION"
    DISPUTED = "DISPUTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    HANDED_OFF = "HANDED_OFF"


class InvoiceMatchLineStatus(StrEnum):
    MATCHED = "MATCHED"
    QUANTITY_VARIANCE = "QUANTITY_VARIANCE"
    PRICE_VARIANCE = "PRICE_VARIANCE"
    TAX_VARIANCE = "TAX_VARIANCE"
    MULTIPLE_VARIANCES = "MULTIPLE_VARIANCES"


class InvoiceMatchExceptionType(StrEnum):
    NONE = "NONE"
    PO_NOT_FOUND = "PO_NOT_FOUND"
    RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    PRICE_MISMATCH = "PRICE_MISMATCH"
    TAX_MISMATCH = "TAX_MISMATCH"
    DUPLICATE_INVOICE = "DUPLICATE_INVOICE"


class SupplierReturnStatus(StrEnum):
    DRAFT = "DRAFT"
    REQUESTED = "REQUESTED"
    AUTHORIZED = "AUTHORIZED"
    DISPATCHED = "DISPATCHED"
    RECEIVED_BY_SUPPLIER = "RECEIVED_BY_SUPPLIER"
    CREDIT_PENDING = "CREDIT_PENDING"
    SETTLED = "SETTLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class SupplierReturnLineStatus(StrEnum):
    PENDING = "PENDING"
    AUTHORIZED = "AUTHORIZED"
    DISPATCHED = "DISPATCHED"
    RECEIVED_BY_SUPPLIER = "RECEIVED_BY_SUPPLIER"
    REJECTED = "REJECTED"
    SETTLED = "SETTLED"


class SupplierReturnReason(StrEnum):
    DAMAGED = "DAMAGED"
    QUALITY_FAILURE = "QUALITY_FAILURE"
    WRONG_ITEM = "WRONG_ITEM"
    EXCESS_QUANTITY = "EXCESS_QUANTITY"
    EXPIRED = "EXPIRED"
    SPECIFICATION_MISMATCH = "SPECIFICATION_MISMATCH"
    RECALL = "RECALL"
    OTHER = "OTHER"


class SupplierClaimStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    DISPUTED = "DISPUTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SETTLED = "SETTLED"


class ApprovalObjectType(StrEnum):
    PURCHASE_REQUISITION = "PURCHASE_REQUISITION"
    PURCHASE_ORDER = "PURCHASE_ORDER"
    INVOICE_MATCH = "INVOICE_MATCH"
    SUPPLIER_RETURN = "SUPPLIER_RETURN"


class ApprovalRequestStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class ApprovalStepStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SKIPPED = "SKIPPED"
