"""add MFA, sessions and password history

Revision ID: 0005_identity_mfa_sessions
Revises: 0004_identity_security
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0005_identity_mfa_sessions"
down_revision = "0004_identity_security"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "identity_user_mfa_settings",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "secret",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            name="uq_identity_user_mfa_settings_user_id",
        ),
    )

    op.create_index(
        "ix_identity_user_mfa_settings_tenant_id",
        "identity_user_mfa_settings",
        ["tenant_id"],
    )
    op.create_index(
        "ix_identity_user_mfa_settings_user_id",
        "identity_user_mfa_settings",
        ["user_id"],
    )

    op.create_table(
        "identity_mfa_recovery_codes",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "code_hash",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "used_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "code_hash",
            name="uq_identity_mfa_recovery_codes_hash",
        ),
    )

    op.create_index(
        "ix_identity_mfa_recovery_codes_tenant_id",
        "identity_mfa_recovery_codes",
        ["tenant_id"],
    )
    op.create_index(
        "ix_identity_mfa_recovery_codes_user_id",
        "identity_mfa_recovery_codes",
        ["user_id"],
    )

    op.create_table(
        "identity_user_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "refresh_token_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "device_name",
            sa.String(length=200),
            nullable=True,
        ),
        sa.Column(
            "is_trusted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "refresh_token_id",
            name="uq_identity_user_sessions_refresh_token_id",
        ),
    )

    op.create_index(
        "ix_identity_user_sessions_tenant_id",
        "identity_user_sessions",
        ["tenant_id"],
    )
    op.create_index(
        "ix_identity_user_sessions_user_id",
        "identity_user_sessions",
        ["user_id"],
    )
    op.create_index(
        "ix_identity_user_sessions_expires_at",
        "identity_user_sessions",
        ["expires_at"],
    )

    op.create_table(
        "identity_password_history",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "password_hash",
            sa.String(length=512),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["identity_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_identity_password_history_tenant_id",
        "identity_password_history",
        ["tenant_id"],
    )
    op.create_index(
        "ix_identity_password_history_user_id",
        "identity_password_history",
        ["user_id"],
    )
    op.create_index(
        "ix_identity_password_history_created_at",
        "identity_password_history",
        ["created_at"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_identity_password_history_created_at",
        table_name="identity_password_history",
    )
    op.drop_index(
        "ix_identity_password_history_user_id",
        table_name="identity_password_history",
    )
    op.drop_index(
        "ix_identity_password_history_tenant_id",
        table_name="identity_password_history",
    )
    op.drop_table("identity_password_history")

    op.drop_index(
        "ix_identity_user_sessions_expires_at",
        table_name="identity_user_sessions",
    )
    op.drop_index(
        "ix_identity_user_sessions_user_id",
        table_name="identity_user_sessions",
    )
    op.drop_index(
        "ix_identity_user_sessions_tenant_id",
        table_name="identity_user_sessions",
    )
    op.drop_table("identity_user_sessions")

    op.drop_index(
        "ix_identity_mfa_recovery_codes_user_id",
        table_name="identity_mfa_recovery_codes",
    )
    op.drop_index(
        "ix_identity_mfa_recovery_codes_tenant_id",
        table_name="identity_mfa_recovery_codes",
    )
    op.drop_table("identity_mfa_recovery_codes")

    op.drop_index(
        "ix_identity_user_mfa_settings_user_id",
        table_name="identity_user_mfa_settings",
    )
    op.drop_index(
        "ix_identity_user_mfa_settings_tenant_id",
        table_name="identity_user_mfa_settings",
    )
    op.drop_table("identity_user_mfa_settings")
