"""add advanced treasury and financial risk foundation

Revision ID: 0008_finance_advanced_treasury
Revises: 0007_finance_treasury
Create Date: 2026-08-06 13:50:26.202733
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0008_finance_advanced_treasury'
down_revision: Union[str, Sequence[str], None] = '0007_finance_treasury'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_treasury_debt_instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('instrument_number', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.Enum('TERM_LOAN', 'REVOLVING_CREDIT', 'OVERDRAFT', 'ISLAMIC_FINANCING', 'BOND', 'LEASE', name='finance_debt_instrument_type'), nullable=False),
    sa.Column('lender_name', sa.String(length=200), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'MATURED', 'REPAID', 'DEFAULTED', 'CANCELLED', name='finance_debt_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_debt_instruments')),
    sa.UniqueConstraint('tenant_id', 'instrument_number', name='uq_finance_debt_instrument_tenant_number')
    )
    op.create_index(op.f('ix_finance_treasury_debt_instruments_tenant_id'), 'finance_treasury_debt_instruments', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_fx_exposures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('exposure_number', sa.String(length=100), nullable=False),
    sa.Column('exposure_type', sa.Enum('RECEIVABLE', 'PAYABLE', 'FORECAST_INFLOW', 'FORECAST_OUTFLOW', 'LOAN', 'INVESTMENT', name='finance_fx_exposure_type'), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('exposure_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('foreign_currency', sa.String(length=3), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('foreign_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('spot_rate', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('hedged_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unhedged_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_HEDGED', 'FULLY_HEDGED', 'SETTLED', 'CANCELLED', name='finance_fx_exposure_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_fx_exposures')),
    sa.UniqueConstraint('tenant_id', 'exposure_number', name='uq_finance_fx_exposure_tenant_number')
    )
    op.create_index(op.f('ix_finance_treasury_fx_exposures_tenant_id'), 'finance_treasury_fx_exposures', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_investments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('investment_number', sa.String(length=100), nullable=False),
    sa.Column('investment_type', sa.Enum('TERM_DEPOSIT', 'MONEY_MARKET', 'GOVERNMENT_SECURITY', 'SUKUK', 'MUTUAL_FUND', name='finance_investment_type'), nullable=False),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('expected_return_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('investment_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('expected_maturity_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'ACTIVE', 'MATURED', 'REDEEMED', 'CANCELLED', name='finance_investment_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_investments')),
    sa.UniqueConstraint('tenant_id', 'investment_number', name='uq_finance_investment_tenant_number')
    )
    op.create_index(op.f('ix_finance_treasury_investments_tenant_id'), 'finance_treasury_investments', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_stress_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('scenario_type', sa.Enum('LIQUIDITY_SHOCK', 'FX_DEPRECIATION', 'INTEREST_RATE_SHOCK', 'CUSTOMER_DEFAULT', 'SUPPLIER_DISRUPTION', 'COMBINED', name='finance_stress_scenario_type'), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=False),
    sa.Column('opening_liquidity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('inflow_reduction_percent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('outflow_increase_percent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('fx_shock_percent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stressed_liquidity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('liquidity_shortfall', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_stress_tests'))
    )
    op.create_index(op.f('ix_finance_treasury_stress_tests_tenant_id'), 'finance_treasury_stress_tests', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_trade_finance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('instrument_number', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.Enum('LETTER_OF_CREDIT', 'BANK_GUARANTEE', 'STANDBY_LC', name='finance_trade_finance_type'), nullable=False),
    sa.Column('issuing_bank', sa.String(length=200), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('utilized_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REQUESTED', 'ISSUED', 'AMENDED', 'UTILIZED', 'EXPIRED', 'RELEASED', 'CANCELLED', name='finance_trade_finance_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_trade_finance')),
    sa.UniqueConstraint('tenant_id', 'instrument_number', name='uq_finance_trade_finance_tenant_number')
    )
    op.create_index(op.f('ix_finance_treasury_trade_finance_tenant_id'), 'finance_treasury_trade_finance', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_hedge_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('exposure_id', sa.UUID(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.Enum('FORWARD', 'FUTURE', 'OPTION', 'SWAP', 'NATURAL_HEDGE', name='finance_hedge_instrument_type'), nullable=False),
    sa.Column('counterparty', sa.String(length=200), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('hedge_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('contracted_rate', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'ACTIVE', 'MATURED', 'TERMINATED', 'CANCELLED', name='finance_hedge_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['exposure_id'], ['finance_treasury_fx_exposures.id'], name=op.f('fk_finance_treasury_hedge_contracts_exposure_id_finance_treasury_fx_exposures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_hedge_contracts')),
    sa.UniqueConstraint('tenant_id', 'contract_number', name='uq_finance_hedge_contract_tenant_number')
    )
    op.create_index(op.f('ix_finance_treasury_hedge_contracts_tenant_id'), 'finance_treasury_hedge_contracts', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_cash_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pool_code', sa.String(length=50), nullable=False),
    sa.Column('pool_name', sa.String(length=200), nullable=False),
    sa.Column('pool_type', sa.Enum('PHYSICAL', 'NOTIONAL', 'ZERO_BALANCE', 'TARGET_BALANCE', name='finance_cash_pool_type'), nullable=False),
    sa.Column('header_bank_account_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('target_balance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='finance_cash_pool_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['header_bank_account_id'], ['finance_bank_accounts.id'], name=op.f('fk_finance_treasury_cash_pools_header_bank_account_id_finance_bank_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_cash_pools')),
    sa.UniqueConstraint('tenant_id', 'pool_code', name='uq_finance_cash_pool_tenant_code')
    )
    op.create_index(op.f('ix_finance_treasury_cash_pools_tenant_id'), 'finance_treasury_cash_pools', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_cash_pool_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('bank_account_id', sa.UUID(), nullable=False),
    sa.Column('minimum_balance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('target_balance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['finance_bank_accounts.id'], name=op.f('fk_finance_treasury_cash_pool_members_bank_account_id_finance_bank_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pool_id'], ['finance_treasury_cash_pools.id'], name=op.f('fk_finance_treasury_cash_pool_members_pool_id_finance_treasury_cash_pools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_cash_pool_members')),
    sa.UniqueConstraint('pool_id', 'bank_account_id', name='uq_finance_cash_pool_member_account')
    )
    op.create_index(op.f('ix_finance_treasury_cash_pool_members_tenant_id'), 'finance_treasury_cash_pool_members', ['tenant_id'], unique=False)
    op.create_table('finance_treasury_intercompany_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('transfer_number', sa.String(length=100), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('source_bank_account_id', sa.UUID(), nullable=False),
    sa.Column('destination_bank_account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('destination_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTED', 'REJECTED', 'CANCELLED', 'FAILED', name='finance_treasury_transfer_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_bank_account_id'], ['finance_bank_accounts.id'], name=op.f('fk_finance_treasury_intercompany_transfers_destination_bank_account_id_finance_bank_accounts')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['finance_journal_entries.id'], name=op.f('fk_finance_treasury_intercompany_transfers_journal_entry_id_finance_journal_entries')),
    sa.ForeignKeyConstraint(['source_bank_account_id'], ['finance_bank_accounts.id'], name=op.f('fk_finance_treasury_intercompany_transfers_source_bank_account_id_finance_bank_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_treasury_intercompany_transfers')),
    sa.UniqueConstraint('tenant_id', 'transfer_number', name='uq_finance_treasury_transfer_tenant_number')
    )
    op.create_index(op.f('ix_finance_treasury_intercompany_transfers_tenant_id'), 'finance_treasury_intercompany_transfers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_bank_reconciliation_matches_tenant_id'), 'finance_bank_reconciliation_matches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_customer_credit_notes_tenant_id'), 'finance_customer_credit_notes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_customer_invoice_lines_invoice_id'), 'finance_customer_invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_finance_customer_invoice_lines_tenant_id'), 'finance_customer_invoice_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_customer_receipts_customer_id'), 'finance_customer_receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_finance_customer_receipts_tenant_id'), 'finance_customer_receipts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_liquidity_forecasts_tenant_id'), 'finance_liquidity_forecasts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_receipt_allocations_invoice_id'), 'finance_receipt_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_finance_receipt_allocations_receipt_id'), 'finance_receipt_allocations', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_finance_receipt_allocations_tenant_id'), 'finance_receipt_allocations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_supplier_invoice_lines_invoice_id'), 'finance_supplier_invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_finance_supplier_invoice_lines_tenant_id'), 'finance_supplier_invoice_lines', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_treasury_batch_approvals_tenant_id'), 'finance_treasury_batch_approvals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_treasury_payment_batches_bank_account_id'), 'finance_treasury_payment_batches', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_finance_treasury_payment_items_batch_id'), 'finance_treasury_payment_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_finance_treasury_payment_items_tenant_id'), 'finance_treasury_payment_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_vendor_debit_notes_tenant_id'), 'finance_vendor_debit_notes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_vendor_payment_allocations_invoice_id'), 'finance_vendor_payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_finance_vendor_payment_allocations_payment_id'), 'finance_vendor_payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_finance_vendor_payment_allocations_tenant_id'), 'finance_vendor_payment_allocations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_vendor_payments_tenant_id'), 'finance_vendor_payments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_vendor_payments_vendor_id'), 'finance_vendor_payments', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_vendor_payments_vendor_id'), table_name='finance_vendor_payments')
    op.drop_index(op.f('ix_finance_vendor_payments_tenant_id'), table_name='finance_vendor_payments')
    op.drop_index(op.f('ix_finance_vendor_payment_allocations_tenant_id'), table_name='finance_vendor_payment_allocations')
    op.drop_index(op.f('ix_finance_vendor_payment_allocations_payment_id'), table_name='finance_vendor_payment_allocations')
    op.drop_index(op.f('ix_finance_vendor_payment_allocations_invoice_id'), table_name='finance_vendor_payment_allocations')
    op.drop_index(op.f('ix_finance_vendor_debit_notes_tenant_id'), table_name='finance_vendor_debit_notes')
    op.drop_index(op.f('ix_finance_treasury_payment_items_tenant_id'), table_name='finance_treasury_payment_items')
    op.drop_index(op.f('ix_finance_treasury_payment_items_batch_id'), table_name='finance_treasury_payment_items')
    op.drop_index(op.f('ix_finance_treasury_payment_batches_bank_account_id'), table_name='finance_treasury_payment_batches')
    op.drop_index(op.f('ix_finance_treasury_batch_approvals_tenant_id'), table_name='finance_treasury_batch_approvals')
    op.drop_index(op.f('ix_finance_supplier_invoice_lines_tenant_id'), table_name='finance_supplier_invoice_lines')
    op.drop_index(op.f('ix_finance_supplier_invoice_lines_invoice_id'), table_name='finance_supplier_invoice_lines')
    op.drop_index(op.f('ix_finance_receipt_allocations_tenant_id'), table_name='finance_receipt_allocations')
    op.drop_index(op.f('ix_finance_receipt_allocations_receipt_id'), table_name='finance_receipt_allocations')
    op.drop_index(op.f('ix_finance_receipt_allocations_invoice_id'), table_name='finance_receipt_allocations')
    op.drop_index(op.f('ix_finance_liquidity_forecasts_tenant_id'), table_name='finance_liquidity_forecasts')
    op.drop_index(op.f('ix_finance_customer_receipts_tenant_id'), table_name='finance_customer_receipts')
    op.drop_index(op.f('ix_finance_customer_receipts_customer_id'), table_name='finance_customer_receipts')
    op.drop_index(op.f('ix_finance_customer_invoice_lines_tenant_id'), table_name='finance_customer_invoice_lines')
    op.drop_index(op.f('ix_finance_customer_invoice_lines_invoice_id'), table_name='finance_customer_invoice_lines')
    op.drop_index(op.f('ix_finance_customer_credit_notes_tenant_id'), table_name='finance_customer_credit_notes')
    op.drop_index(op.f('ix_finance_bank_reconciliation_matches_tenant_id'), table_name='finance_bank_reconciliation_matches')
    op.drop_index(op.f('ix_finance_treasury_intercompany_transfers_tenant_id'), table_name='finance_treasury_intercompany_transfers')
    op.drop_table('finance_treasury_intercompany_transfers')
    op.drop_index(op.f('ix_finance_treasury_cash_pool_members_tenant_id'), table_name='finance_treasury_cash_pool_members')
    op.drop_table('finance_treasury_cash_pool_members')
    op.drop_index(op.f('ix_finance_treasury_cash_pools_tenant_id'), table_name='finance_treasury_cash_pools')
    op.drop_table('finance_treasury_cash_pools')
    op.drop_index(op.f('ix_finance_treasury_hedge_contracts_tenant_id'), table_name='finance_treasury_hedge_contracts')
    op.drop_table('finance_treasury_hedge_contracts')
    op.drop_index(op.f('ix_finance_treasury_trade_finance_tenant_id'), table_name='finance_treasury_trade_finance')
    op.drop_table('finance_treasury_trade_finance')
    op.drop_index(op.f('ix_finance_treasury_stress_tests_tenant_id'), table_name='finance_treasury_stress_tests')
    op.drop_table('finance_treasury_stress_tests')
    op.drop_index(op.f('ix_finance_treasury_investments_tenant_id'), table_name='finance_treasury_investments')
    op.drop_table('finance_treasury_investments')
    op.drop_index(op.f('ix_finance_treasury_fx_exposures_tenant_id'), table_name='finance_treasury_fx_exposures')
    op.drop_table('finance_treasury_fx_exposures')
    op.drop_index(op.f('ix_finance_treasury_debt_instruments_tenant_id'), table_name='finance_treasury_debt_instruments')
    op.drop_table('finance_treasury_debt_instruments')
    # ### end Alembic commands ###
