"""add budgeting forecasting and cost management

Revision ID: 0009_finance_budgeting
Revises: 0008_finance_advanced_treasury
Create Date: 2026-08-06 15:52:15.925869
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0009_finance_budgeting'
down_revision: Union[str, Sequence[str], None] = '0008_finance_advanced_treasury'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_cost_centres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('object_type', sa.Enum('CORPORATE', 'FARM', 'BRANCH', 'DEPARTMENT', 'COST_CENTRE', 'PROFIT_CENTRE', 'CROP', 'LIVESTOCK', 'DAIRY', 'POULTRY', 'MANUFACTURING', 'PROJECT', name='finance_cost_object_type'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_cost_centres.id'], name=op.f('fk_finance_cost_centres_parent_id_finance_cost_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_cost_centres')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_finance_cost_centre_tenant_code')
    )
    op.create_index(op.f('ix_finance_cost_centres_tenant_id'), 'finance_cost_centres', ['tenant_id'], unique=False)
    op.create_table('finance_cost_variances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('variance_date', sa.Date(), nullable=False),
    sa.Column('variance_type', sa.Enum('PRICE', 'QUANTITY', 'LABOUR_RATE', 'LABOUR_EFFICIENCY', 'OVERHEAD_SPENDING', 'OVERHEAD_VOLUME', 'SALES_VOLUME', 'BUDGET_ACTUAL', name='finance_variance_type'), nullable=False),
    sa.Column('object_type', sa.Enum('CORPORATE', 'FARM', 'BRANCH', 'DEPARTMENT', 'COST_CENTRE', 'PROFIT_CENTRE', 'CROP', 'LIVESTOCK', 'DAIRY', 'POULTRY', 'MANUFACTURING', 'PROJECT', name='finance_variance_object_type'), nullable=False),
    sa.Column('object_reference', sa.String(length=200), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('variance_percent', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_favourable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_cost_variances'))
    )
    op.create_index(op.f('ix_finance_cost_variances_tenant_id'), 'finance_cost_variances', ['tenant_id'], unique=False)
    op.create_table('finance_profit_centres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('object_type', sa.Enum('CORPORATE', 'FARM', 'BRANCH', 'DEPARTMENT', 'COST_CENTRE', 'PROFIT_CENTRE', 'CROP', 'LIVESTOCK', 'DAIRY', 'POULTRY', 'MANUFACTURING', 'PROJECT', name='finance_profit_object_type'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_profit_centres.id'], name=op.f('fk_finance_profit_centres_parent_id_finance_profit_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_profit_centres')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_finance_profit_centre_tenant_code')
    )
    op.create_index(op.f('ix_finance_profit_centres_tenant_id'), 'finance_profit_centres', ['tenant_id'], unique=False)
    op.create_table('finance_standard_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.Enum('CORPORATE', 'FARM', 'BRANCH', 'DEPARTMENT', 'COST_CENTRE', 'PROFIT_CENTRE', 'CROP', 'LIVESTOCK', 'DAIRY', 'POULTRY', 'MANUFACTURING', 'PROJECT', name='finance_standard_cost_object_type'), nullable=False),
    sa.Column('object_reference', sa.String(length=200), nullable=False),
    sa.Column('costing_method', sa.Enum('ACTUAL', 'STANDARD', 'AVERAGE', 'ACTIVITY_BASED', name='finance_costing_method'), nullable=False),
    sa.Column('material_cost', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('labour_cost', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('overhead_cost', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('total_standard_cost', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_standard_costs')),
    sa.UniqueConstraint('tenant_id', 'object_type', 'object_reference', 'effective_from', name='uq_finance_standard_cost_scope')
    )
    op.create_index(op.f('ix_finance_standard_costs_tenant_id'), 'finance_standard_costs', ['tenant_id'], unique=False)
    op.create_table('finance_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('budget_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('budget_type', sa.Enum('ANNUAL', 'ROLLING', 'CAPITAL', 'CASH_FLOW', 'OPERATIONAL', name='finance_budget_type'), nullable=False),
    sa.Column('fiscal_year_id', sa.UUID(), nullable=False),
    sa.Column('scenario', sa.Enum('BASE', 'OPTIMISTIC', 'CONSERVATIVE', 'STRESS', name='finance_planning_scenario'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ACTIVE', 'CLOSED', 'CANCELLED', name='finance_budget_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['finance_fiscal_years.id'], name=op.f('fk_finance_budgets_fiscal_year_id_finance_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_budgets')),
    sa.UniqueConstraint('tenant_id', 'budget_number', name='uq_finance_budget_tenant_number')
    )
    op.create_index(op.f('ix_finance_budgets_tenant_id'), 'finance_budgets', ['tenant_id'], unique=False)
    op.create_table('finance_cost_allocation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('allocation_method', sa.Enum('FIXED_PERCENTAGE', 'HEADCOUNT', 'AREA', 'PRODUCTION_VOLUME', 'REVENUE', 'DIRECT_COST', 'ACTIVITY_BASED', name='finance_cost_allocation_method'), nullable=False),
    sa.Column('source_cost_centre_id', sa.UUID(), nullable=False),
    sa.Column('target_object_type', sa.Enum('CORPORATE', 'FARM', 'BRANCH', 'DEPARTMENT', 'COST_CENTRE', 'PROFIT_CENTRE', 'CROP', 'LIVESTOCK', 'DAIRY', 'POULTRY', 'MANUFACTURING', 'PROJECT', name='finance_allocation_target_object_type'), nullable=False),
    sa.Column('basis_reference', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_cost_centre_id'], ['finance_cost_centres.id'], name=op.f('fk_finance_cost_allocation_rules_source_cost_centre_id_finance_cost_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_cost_allocation_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', name='uq_finance_allocation_rule_tenant_code')
    )
    op.create_index(op.f('ix_finance_cost_allocation_rules_tenant_id'), 'finance_cost_allocation_rules', ['tenant_id'], unique=False)
    op.create_table('finance_budget_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'BASELINE', 'SUPERSEDED', 'ARCHIVED', name='finance_budget_version_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['finance_budgets.id'], name=op.f('fk_finance_budget_versions_budget_id_finance_budgets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_budget_versions')),
    sa.UniqueConstraint('budget_id', 'version_number', name='uq_finance_budget_version_number')
    )
    op.create_index(op.f('ix_finance_budget_versions_tenant_id'), 'finance_budget_versions', ['tenant_id'], unique=False)
    op.create_table('finance_budget_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('ledger_account_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('cost_centre_id', sa.UUID(), nullable=True),
    sa.Column('profit_centre_id', sa.UUID(), nullable=True),
    sa.Column('object_type', sa.Enum('CORPORATE', 'FARM', 'BRANCH', 'DEPARTMENT', 'COST_CENTRE', 'PROFIT_CENTRE', 'CROP', 'LIVESTOCK', 'DAIRY', 'POULTRY', 'MANUFACTURING', 'PROJECT', name='finance_budget_object_type'), nullable=False),
    sa.Column('object_reference', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['finance_cost_centres.id'], name=op.f('fk_finance_budget_lines_cost_centre_id_finance_cost_centres')),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['finance_fiscal_periods.id'], name=op.f('fk_finance_budget_lines_fiscal_period_id_finance_fiscal_periods')),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_budget_lines_ledger_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['profit_centre_id'], ['finance_profit_centres.id'], name=op.f('fk_finance_budget_lines_profit_centre_id_finance_profit_centres')),
    sa.ForeignKeyConstraint(['version_id'], ['finance_budget_versions.id'], name=op.f('fk_finance_budget_lines_version_id_finance_budget_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_budget_lines')),
    sa.UniqueConstraint('version_id', 'line_number', name='uq_finance_budget_line_version_number')
    )
    op.create_index(op.f('ix_finance_budget_lines_tenant_id'), 'finance_budget_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_budget_lines_tenant_id'), table_name='finance_budget_lines')
    op.drop_table('finance_budget_lines')
    op.drop_index(op.f('ix_finance_budget_versions_tenant_id'), table_name='finance_budget_versions')
    op.drop_table('finance_budget_versions')
    op.drop_index(op.f('ix_finance_cost_allocation_rules_tenant_id'), table_name='finance_cost_allocation_rules')
    op.drop_table('finance_cost_allocation_rules')
    op.drop_index(op.f('ix_finance_budgets_tenant_id'), table_name='finance_budgets')
    op.drop_table('finance_budgets')
    op.drop_index(op.f('ix_finance_standard_costs_tenant_id'), table_name='finance_standard_costs')
    op.drop_table('finance_standard_costs')
    op.drop_index(op.f('ix_finance_profit_centres_tenant_id'), table_name='finance_profit_centres')
    op.drop_table('finance_profit_centres')
    op.drop_index(op.f('ix_finance_cost_variances_tenant_id'), table_name='finance_cost_variances')
    op.drop_table('finance_cost_variances')
    op.drop_index(op.f('ix_finance_cost_centres_tenant_id'), table_name='finance_cost_centres')
    op.drop_table('finance_cost_centres')
    # ### end Alembic commands ###
