"""add fixed assets depreciation and capital projects

Revision ID: 0010_finance_fixed_assets
Revises: 0009_finance_budgeting
Create Date: 2026-08-06 16:24:26.094866
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0010_finance_fixed_assets'
down_revision: Union[str, Sequence[str], None] = '0009_finance_budgeting'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_asset_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_asset_locations.id'], name=op.f('fk_finance_asset_locations_parent_id_finance_asset_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_locations')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_finance_asset_location_tenant_code')
    )
    op.create_index(op.f('ix_finance_asset_locations_tenant_id'), 'finance_asset_locations', ['tenant_id'], unique=False)
    op.create_table('finance_asset_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('default_useful_life_months', sa.Integer(), nullable=False),
    sa.Column('default_depreciation_method', sa.Enum('STRAIGHT_LINE', 'REDUCING_BALANCE', 'UNITS_OF_PRODUCTION', 'NO_DEPRECIATION', name='finance_asset_default_depreciation_method'), nullable=False),
    sa.Column('asset_account_id', sa.UUID(), nullable=False),
    sa.Column('accumulated_depreciation_account_id', sa.UUID(), nullable=False),
    sa.Column('depreciation_expense_account_id', sa.UUID(), nullable=False),
    sa.Column('disposal_gain_account_id', sa.UUID(), nullable=True),
    sa.Column('disposal_loss_account_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_asset_categories_accumulated_depreciation_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['asset_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_asset_categories_asset_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['depreciation_expense_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_asset_categories_depreciation_expense_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['disposal_gain_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_asset_categories_disposal_gain_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['disposal_loss_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_asset_categories_disposal_loss_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_asset_categories.id'], name=op.f('fk_finance_asset_categories_parent_id_finance_asset_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_categories')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_finance_asset_category_tenant_code')
    )
    op.create_index(op.f('ix_finance_asset_categories_tenant_id'), 'finance_asset_categories', ['tenant_id'], unique=False)
    op.create_table('finance_fixed_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('custodian_id', sa.UUID(), nullable=True),
    sa.Column('cost_centre_id', sa.UUID(), nullable=True),
    sa.Column('profit_centre_id', sa.UUID(), nullable=True),
    sa.Column('acquisition_type', sa.Enum('PURCHASE', 'CONSTRUCTION', 'LEASE', 'DONATION', 'TRANSFER_IN', 'OPENING_BALANCE', name='finance_asset_acquisition_type'), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('capitalization_date', sa.Date(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('source_document_reference', sa.String(length=200), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('impairment_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('revaluation_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('net_book_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.Enum('STRAIGHT_LINE', 'REDUCING_BALANCE', 'UNITS_OF_PRODUCTION', 'NO_DEPRECIATION', name='finance_asset_depreciation_method'), nullable=False),
    sa.Column('depreciation_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_total_units', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('units_consumed', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'UNDER_MAINTENANCE', 'IDLE', 'IMPAIRED', 'HELD_FOR_SALE', 'DISPOSED', 'RETIRED', name='finance_asset_status'), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('qr_code', sa.String(length=500), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model_number', sa.String(length=200), nullable=True),
    sa.Column('cmms_asset_reference', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finance_asset_categories.id'], name=op.f('fk_finance_fixed_assets_category_id_finance_asset_categories')),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['finance_cost_centres.id'], name=op.f('fk_finance_fixed_assets_cost_centre_id_finance_cost_centres')),
    sa.ForeignKeyConstraint(['location_id'], ['finance_asset_locations.id'], name=op.f('fk_finance_fixed_assets_location_id_finance_asset_locations')),
    sa.ForeignKeyConstraint(['profit_centre_id'], ['finance_profit_centres.id'], name=op.f('fk_finance_fixed_assets_profit_centre_id_finance_profit_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_fixed_assets')),
    sa.UniqueConstraint('tenant_id', 'asset_number', name='uq_finance_fixed_asset_tenant_number'),
    sa.UniqueConstraint('tenant_id', 'barcode', name='uq_finance_fixed_asset_tenant_barcode')
    )
    op.create_index(op.f('ix_finance_fixed_assets_tenant_id'), 'finance_fixed_assets', ['tenant_id'], unique=False)
    op.create_table('finance_asset_capital_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'IN_PROGRESS', 'READY_FOR_CAPITALIZATION', 'CAPITALIZED', 'CANCELLED', name='finance_asset_project_status'), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('accumulated_cost', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('cwip_account_id', sa.UUID(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('capitalized_asset_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['capitalized_asset_id'], ['finance_fixed_assets.id'], name=op.f('fk_finance_asset_capital_projects_capitalized_asset_id_finance_fixed_assets')),
    sa.ForeignKeyConstraint(['cwip_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_asset_capital_projects_cwip_account_id_finance_ledger_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_capital_projects')),
    sa.UniqueConstraint('tenant_id', 'project_number', name='uq_finance_asset_project_tenant_number')
    )
    op.create_index(op.f('ix_finance_asset_capital_projects_tenant_id'), 'finance_asset_capital_projects', ['tenant_id'], unique=False)
    op.create_table('finance_asset_depreciation_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('book_type', sa.Enum('IFRS', 'TAX', 'MANAGEMENT', name='finance_asset_depreciation_book_type'), nullable=False),
    sa.Column('depreciation_method', sa.Enum('STRAIGHT_LINE', 'REDUCING_BALANCE', 'UNITS_OF_PRODUCTION', 'NO_DEPRECIATION', name='finance_asset_book_depreciation_method'), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('annual_rate_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('residual_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('net_book_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('last_depreciation_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_fixed_assets.id'], name=op.f('fk_finance_asset_depreciation_books_asset_id_finance_fixed_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_depreciation_books')),
    sa.UniqueConstraint('asset_id', 'book_type', name='uq_finance_asset_depreciation_book')
    )
    op.create_index(op.f('ix_finance_asset_depreciation_books_tenant_id'), 'finance_asset_depreciation_books', ['tenant_id'], unique=False)
    op.create_table('finance_asset_disposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('disposal_type', sa.Enum('SALE', 'SCRAP', 'DONATION', 'WRITE_OFF', 'TRADE_IN', name='finance_asset_disposal_type'), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('disposal_costs', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('net_book_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('gain_loss', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('buyer_reference', sa.String(length=200), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('disposed_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_fixed_assets.id'], name=op.f('fk_finance_asset_disposals_asset_id_finance_fixed_assets')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['finance_journal_entries.id'], name=op.f('fk_finance_asset_disposals_journal_entry_id_finance_journal_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_disposals')),
    sa.UniqueConstraint('asset_id', name='uq_finance_asset_disposal_asset')
    )
    op.create_index(op.f('ix_finance_asset_disposals_tenant_id'), 'finance_asset_disposals', ['tenant_id'], unique=False)
    op.create_table('finance_asset_insurance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('insurer_name', sa.String(length=200), nullable=False),
    sa.Column('policy_number', sa.String(length=200), nullable=False),
    sa.Column('coverage_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('premium_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_fixed_assets.id'], name=op.f('fk_finance_asset_insurance_asset_id_finance_fixed_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_insurance'))
    )
    op.create_index(op.f('ix_finance_asset_insurance_tenant_id'), 'finance_asset_insurance', ['tenant_id'], unique=False)
    op.create_table('finance_asset_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('transaction_type', sa.Enum('ACQUISITION', 'CAPITALIZATION', 'DEPRECIATION', 'TRANSFER', 'REVALUATION', 'IMPAIRMENT', 'DISPOSAL', 'RETIREMENT', name='finance_asset_transaction_type'), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('from_location_id', sa.UUID(), nullable=True),
    sa.Column('to_location_id', sa.UUID(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_fixed_assets.id'], name=op.f('fk_finance_asset_transactions_asset_id_finance_fixed_assets')),
    sa.ForeignKeyConstraint(['from_location_id'], ['finance_asset_locations.id'], name=op.f('fk_finance_asset_transactions_from_location_id_finance_asset_locations')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['finance_journal_entries.id'], name=op.f('fk_finance_asset_transactions_journal_entry_id_finance_journal_entries')),
    sa.ForeignKeyConstraint(['to_location_id'], ['finance_asset_locations.id'], name=op.f('fk_finance_asset_transactions_to_location_id_finance_asset_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_transactions')),
    sa.UniqueConstraint('tenant_id', 'transaction_number', name='uq_finance_asset_transaction_tenant_number')
    )
    op.create_index(op.f('ix_finance_asset_transactions_tenant_id'), 'finance_asset_transactions', ['tenant_id'], unique=False)
    op.create_table('finance_asset_warranties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('warranty_number', sa.String(length=200), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['finance_fixed_assets.id'], name=op.f('fk_finance_asset_warranties_asset_id_finance_fixed_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_asset_warranties'))
    )
    op.create_index(op.f('ix_finance_asset_warranties_tenant_id'), 'finance_asset_warranties', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_asset_warranties_tenant_id'), table_name='finance_asset_warranties')
    op.drop_table('finance_asset_warranties')
    op.drop_index(op.f('ix_finance_asset_transactions_tenant_id'), table_name='finance_asset_transactions')
    op.drop_table('finance_asset_transactions')
    op.drop_index(op.f('ix_finance_asset_insurance_tenant_id'), table_name='finance_asset_insurance')
    op.drop_table('finance_asset_insurance')
    op.drop_index(op.f('ix_finance_asset_disposals_tenant_id'), table_name='finance_asset_disposals')
    op.drop_table('finance_asset_disposals')
    op.drop_index(op.f('ix_finance_asset_depreciation_books_tenant_id'), table_name='finance_asset_depreciation_books')
    op.drop_table('finance_asset_depreciation_books')
    op.drop_index(op.f('ix_finance_asset_capital_projects_tenant_id'), table_name='finance_asset_capital_projects')
    op.drop_table('finance_asset_capital_projects')
    op.drop_index(op.f('ix_finance_fixed_assets_tenant_id'), table_name='finance_fixed_assets')
    op.drop_table('finance_fixed_assets')
    op.drop_index(op.f('ix_finance_asset_categories_tenant_id'), table_name='finance_asset_categories')
    op.drop_table('finance_asset_categories')
    op.drop_index(op.f('ix_finance_asset_locations_tenant_id'), table_name='finance_asset_locations')
    op.drop_table('finance_asset_locations')
    # ### end Alembic commands ###
