"""add intercompany accounting and consolidation

Revision ID: 0011_finance_intercompany
Revises: 0010_finance_fixed_assets
Create Date: 2026-08-07 01:15:26.670987
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0011_finance_intercompany'
down_revision: Union[str, Sequence[str], None] = '0010_finance_fixed_assets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_intercompany_organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_code', sa.String(length=50), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_intercompany_organizations')),
    sa.UniqueConstraint('tenant_id', 'organization_code', name='uq_ic_org_code')
    )
    op.create_index(op.f('ix_finance_intercompany_organizations_tenant_id'), 'finance_intercompany_organizations', ['tenant_id'], unique=False)
    op.create_index('ix_ic_org_tenant', 'finance_intercompany_organizations', ['tenant_id'], unique=False)
    op.create_table('finance_consolidation_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('parent_organization_id', sa.UUID(), nullable=False),
    sa.Column('presentation_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'CLOSED', name='finance_consolidation_group_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_organization_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_consolidation_groups_parent_organization_id_finance_intercompany_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_consolidation_groups')),
    sa.UniqueConstraint('tenant_id', 'group_code', name='uq_finance_consolidation_group_tenant_code')
    )
    op.create_index('ix_finance_consolidation_group_tenant', 'finance_consolidation_groups', ['tenant_id'], unique=False)
    op.create_table('finance_intercompany_account_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_organization_id', sa.UUID(), nullable=False),
    sa.Column('destination_organization_id', sa.UUID(), nullable=False),
    sa.Column('source_due_from_account_id', sa.UUID(), nullable=False),
    sa.Column('source_due_to_account_id', sa.UUID(), nullable=False),
    sa.Column('destination_due_from_account_id', sa.UUID(), nullable=False),
    sa.Column('destination_due_to_account_id', sa.UUID(), nullable=False),
    sa.Column('settlement_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_organization_id <> destination_organization_id', name=op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies')),
    sa.ForeignKeyConstraint(['destination_due_from_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_intercompany_account_mappings_destination_due_from_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_due_to_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_intercompany_account_mappings_destination_due_to_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_organization_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_intercompany_account_mappings_destination_organization_id_finance_intercompany_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_due_from_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_intercompany_account_mappings_source_due_from_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_due_to_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_intercompany_account_mappings_source_due_to_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_organization_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_intercompany_account_mappings_source_organization_id_finance_intercompany_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_intercompany_account_mappings')),
    sa.UniqueConstraint('tenant_id', 'source_organization_id', 'destination_organization_id', name='uq_ic_account_mapping_company_pair')
    )
    op.create_index('ix_ic_account_mapping_tenant', 'finance_intercompany_account_mappings', ['tenant_id'], unique=False)
    op.create_table('finance_intercompany_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('parent_company_id', sa.UUID(), nullable=False),
    sa.Column('child_company_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PARENT_SUBSIDIARY', 'SISTER_COMPANY', 'JOINT_VENTURE', 'ASSOCIATE', name='finance_intercompany_relationship_type'), nullable=False),
    sa.Column('ownership_percentage', sa.Integer(), nullable=False),
    sa.Column('voting_percentage', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_company_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_intercompany_relationships_child_company_id_finance_intercompany_organizations')),
    sa.ForeignKeyConstraint(['parent_company_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_intercompany_relationships_parent_company_id_finance_intercompany_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_intercompany_relationships')),
    sa.UniqueConstraint('tenant_id', 'parent_company_id', 'child_company_id', name='uq_ic_relationship')
    )
    op.create_index('ix_ic_relationship_tenant', 'finance_intercompany_relationships', ['tenant_id'], unique=False)
    op.create_table('finance_consolidation_group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('consolidation_method', sa.Enum('FULL', 'PROPORTIONATE', 'EQUITY', name='finance_consolidation_member_method'), nullable=False),
    sa.Column('ownership_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('voting_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('ownership_percentage >= 0 AND ownership_percentage <= 100', name=op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage')),
    sa.CheckConstraint('voting_percentage >= 0 AND voting_percentage <= 100', name=op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage')),
    sa.ForeignKeyConstraint(['group_id'], ['finance_consolidation_groups.id'], name=op.f('fk_finance_consolidation_group_members_group_id_finance_consolidation_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_consolidation_group_members_organization_id_finance_intercompany_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_consolidation_group_members')),
    sa.UniqueConstraint('group_id', 'organization_id', name='uq_finance_consolidation_group_member')
    )
    op.create_index('ix_finance_consolidation_member_tenant', 'finance_consolidation_group_members', ['tenant_id'], unique=False)
    op.create_table('finance_consolidation_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DATA_COLLECTION', 'TRANSLATION', 'ELIMINATION', 'REVIEW', 'CLOSED', 'REOPENED', name='finance_consolidation_period_status'), nullable=False),
    sa.Column('presentation_currency', sa.String(length=3), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range')),
    sa.ForeignKeyConstraint(['group_id'], ['finance_consolidation_groups.id'], name=op.f('fk_finance_consolidation_periods_group_id_finance_consolidation_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_consolidation_periods')),
    sa.UniqueConstraint('group_id', 'period_start', 'period_end', name='uq_finance_consolidation_period_range')
    )
    op.create_index('ix_finance_consolidation_period_tenant', 'finance_consolidation_periods', ['tenant_id'], unique=False)
    op.create_table('finance_currency_translation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('rate_type', sa.Enum('CLOSING', 'AVERAGE', 'HISTORICAL', name='finance_translation_rate_type'), nullable=False),
    sa.Column('translation_adjustment_account_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['finance_consolidation_groups.id'], name=op.f('fk_finance_currency_translation_rules_group_id_finance_consolidation_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translation_adjustment_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_currency_translation_rules_translation_adjustment_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_currency_translation_rules')),
    sa.UniqueConstraint('tenant_id', 'group_id', 'account_type', name='uq_finance_translation_rule_scope')
    )
    op.create_index('ix_finance_translation_rule_tenant', 'finance_currency_translation_rules', ['tenant_id'], unique=False)
    op.create_table('finance_elimination_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', 'INVESTMENT_EQUITY', 'INTERCOMPANY_PROFIT', 'DIVIDEND', name='finance_elimination_rule_type'), nullable=False),
    sa.Column('source_account_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_account_id', sa.UUID(), nullable=False),
    sa.Column('elimination_account_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_elimination_rules_counterparty_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['elimination_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_elimination_rules_elimination_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['finance_consolidation_groups.id'], name=op.f('fk_finance_elimination_rules_group_id_finance_consolidation_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_elimination_rules_source_account_id_finance_ledger_accounts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_elimination_rules')),
    sa.UniqueConstraint('tenant_id', 'group_id', 'rule_code', name='uq_finance_elimination_rule_code')
    )
    op.create_index('ix_finance_elimination_rule_tenant', 'finance_elimination_rules', ['tenant_id'], unique=False)
    op.create_table('finance_intercompany_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('source_organization_id', sa.UUID(), nullable=False),
    sa.Column('destination_organization_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('source_journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('destination_journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('destination_reference', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'MATCHED', 'SETTLED', 'ELIMINATED', 'DISPUTED', 'CANCELLED', name='finance_intercompany_transaction_status'), nullable=False),
    sa.Column('elimination_period_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount')),
    sa.CheckConstraint('source_organization_id <> destination_organization_id', name=op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies')),
    sa.ForeignKeyConstraint(['destination_journal_entry_id'], ['finance_journal_entries.id'], name=op.f('fk_finance_intercompany_transactions_destination_journal_entry_id_finance_journal_entries')),
    sa.ForeignKeyConstraint(['destination_organization_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_intercompany_transactions_destination_organization_id_finance_intercompany_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['elimination_period_id'], ['finance_consolidation_periods.id'], name=op.f('fk_finance_intercompany_transactions_elimination_period_id_finance_consolidation_periods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_journal_entry_id'], ['finance_journal_entries.id'], name=op.f('fk_finance_intercompany_transactions_source_journal_entry_id_finance_journal_entries')),
    sa.ForeignKeyConstraint(['source_organization_id'], ['finance_intercompany_organizations.id'], name=op.f('fk_finance_intercompany_transactions_source_organization_id_finance_intercompany_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_intercompany_transactions')),
    sa.UniqueConstraint('tenant_id', 'transaction_number', name='uq_finance_intercompany_transaction_number')
    )
    op.create_index('ix_finance_intercompany_transaction_tenant', 'finance_intercompany_transactions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finance_intercompany_transaction_tenant', table_name='finance_intercompany_transactions')
    op.drop_table('finance_intercompany_transactions')
    op.drop_index('ix_finance_elimination_rule_tenant', table_name='finance_elimination_rules')
    op.drop_table('finance_elimination_rules')
    op.drop_index('ix_finance_translation_rule_tenant', table_name='finance_currency_translation_rules')
    op.drop_table('finance_currency_translation_rules')
    op.drop_index('ix_finance_consolidation_period_tenant', table_name='finance_consolidation_periods')
    op.drop_table('finance_consolidation_periods')
    op.drop_index('ix_finance_consolidation_member_tenant', table_name='finance_consolidation_group_members')
    op.drop_table('finance_consolidation_group_members')
    op.drop_index('ix_ic_relationship_tenant', table_name='finance_intercompany_relationships')
    op.drop_table('finance_intercompany_relationships')
    op.drop_index('ix_ic_account_mapping_tenant', table_name='finance_intercompany_account_mappings')
    op.drop_table('finance_intercompany_account_mappings')
    op.drop_index('ix_finance_consolidation_group_tenant', table_name='finance_consolidation_groups')
    op.drop_table('finance_consolidation_groups')
    op.drop_index('ix_ic_org_tenant', table_name='finance_intercompany_organizations')
    op.drop_index(op.f('ix_finance_intercompany_organizations_tenant_id'), table_name='finance_intercompany_organizations')
    op.drop_table('finance_intercompany_organizations')
    # ### end Alembic commands ###
