"""add financial close automation and period controls

Revision ID: 0012_finance_close
Revises: 0011_finance_intercompany
Create Date: 2026-08-07 01:36:28.735723
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0012_finance_close'
down_revision: Union[str, Sequence[str], None] = '0011_finance_intercompany'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_close_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cycle_code', sa.String(length=100), nullable=False),
    sa.Column('cycle_name', sa.String(length=255), nullable=False),
    sa.Column('cycle_type', sa.Enum('MONTH_END', 'QUARTER_END', 'YEAR_END', 'SPECIAL', name='finance_close_cycle_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=True),
    sa.Column('consolidation_period_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'IN_PROGRESS', 'REVIEW', 'SOFT_CLOSED', 'HARD_CLOSED', 'REOPENED', 'CANCELLED', name='finance_close_status'), nullable=False),
    sa.Column('materiality_threshold', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('planned_close_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_finance_close_cycles_ck_finance_close_cycle_valid_period')),
    sa.ForeignKeyConstraint(['consolidation_period_id'], ['finance_consolidation_periods.id'], name=op.f('fk_finance_close_cycles_consolidation_period_id_finance_consolidation_periods')),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['finance_fiscal_periods.id'], name=op.f('fk_finance_close_cycles_fiscal_period_id_finance_fiscal_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_close_cycles')),
    sa.UniqueConstraint('tenant_id', 'cycle_code', name='uq_finance_close_cycle_tenant_code')
    )
    op.create_index('ix_finance_close_cycle_tenant', 'finance_close_cycles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_close_cycles_tenant_id'), 'finance_close_cycles', ['tenant_id'], unique=False)
    op.create_table('finance_close_audit_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('package_number', sa.String(length=100), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('document_reference', sa.String(length=500), nullable=False),
    sa.Column('package_hash', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['finance_close_cycles.id'], name=op.f('fk_finance_close_audit_packages_cycle_id_finance_close_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_close_audit_packages')),
    sa.UniqueConstraint('tenant_id', 'package_number', name='uq_finance_close_audit_package_number')
    )
    op.create_index('ix_finance_close_audit_package_tenant', 'finance_close_audit_packages', ['tenant_id'], unique=False)
    op.create_table('finance_close_signoffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('PREPARER', 'REVIEWER', 'CONTROLLER', 'CFO', 'AUDITOR', name='finance_close_signoff_role'), nullable=False),
    sa.Column('signer_id', sa.UUID(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['finance_close_cycles.id'], name=op.f('fk_finance_close_signoffs_cycle_id_finance_close_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_close_signoffs')),
    sa.UniqueConstraint('cycle_id', 'role', name='uq_finance_close_signoff_cycle_role')
    )
    op.create_index('ix_finance_close_signoff_tenant', 'finance_close_signoffs', ['tenant_id'], unique=False)
    op.create_table('finance_close_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('task_code', sa.String(length=100), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.Enum('JOURNAL_REVIEW', 'BANK_RECONCILIATION', 'AR_RECONCILIATION', 'AP_RECONCILIATION', 'INVENTORY_RECONCILIATION', 'FIXED_ASSET_DEPRECIATION', 'INTERCOMPANY_RECONCILIATION', 'FX_TRANSLATION', 'ELIMINATION', 'TRIAL_BALANCE_VALIDATION', 'FINANCIAL_STATEMENTS', 'MANAGEMENT_REVIEW', 'AUDIT_PACKAGE', 'PERIOD_LOCK', 'YEAR_END_ROLLOVER', name='finance_close_task_type'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'WAIVED', name='finance_close_task_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['finance_close_cycles.id'], name=op.f('fk_finance_close_tasks_cycle_id_finance_close_cycles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_close_tasks')),
    sa.UniqueConstraint('cycle_id', 'task_code', name='uq_finance_close_task_cycle_code')
    )
    op.create_index('ix_finance_close_task_cycle_status', 'finance_close_tasks', ['cycle_id', 'status'], unique=False)
    op.create_index('ix_finance_close_task_tenant', 'finance_close_tasks', ['tenant_id'], unique=False)
    op.create_table('finance_period_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=True),
    sa.Column('lock_type', sa.Enum('SOFT', 'HARD', name='finance_period_lock_type'), nullable=False),
    sa.Column('locked_by', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlocked_by', sa.UUID(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['finance_close_cycles.id'], name=op.f('fk_finance_period_locks_cycle_id_finance_close_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['finance_fiscal_periods.id'], name=op.f('fk_finance_period_locks_fiscal_period_id_finance_fiscal_periods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_period_locks')),
    sa.UniqueConstraint('tenant_id', 'fiscal_period_id', 'lock_type', name='uq_finance_period_lock_scope')
    )
    op.create_index('ix_finance_period_lock_tenant', 'finance_period_locks', ['tenant_id'], unique=False)
    op.create_table('finance_close_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('exception_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='finance_close_exception_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'WAIVED', name='finance_close_exception_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('is_material', sa.Boolean(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['finance_close_cycles.id'], name=op.f('fk_finance_close_exceptions_cycle_id_finance_close_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['finance_close_tasks.id'], name=op.f('fk_finance_close_exceptions_task_id_finance_close_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_close_exceptions')),
    sa.UniqueConstraint('tenant_id', 'exception_number', name='uq_finance_close_exception_number')
    )
    op.create_index('ix_finance_close_exception_cycle_status', 'finance_close_exceptions', ['cycle_id', 'status'], unique=False)
    op.create_index(op.f('ix_finance_close_exceptions_tenant_id'), 'finance_close_exceptions', ['tenant_id'], unique=False)
    op.create_table('finance_close_task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name=op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency')),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['finance_close_tasks.id'], name=op.f('fk_finance_close_task_dependencies_depends_on_task_id_finance_close_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['finance_close_tasks.id'], name=op.f('fk_finance_close_task_dependencies_task_id_finance_close_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_close_task_dependencies')),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_finance_close_task_dependency')
    )
    op.create_index(op.f('ix_finance_close_task_dependencies_tenant_id'), 'finance_close_task_dependencies', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', 'ownership_percentage >= 0 AND ownership_percentage <= 100')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', 'voting_percentage >= 0 AND voting_percentage <= 100')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', 'amount > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', 'amount > 0::numeric')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', 'voting_percentage >= 0::numeric AND voting_percentage <= 100::numeric')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', 'ownership_percentage >= 0::numeric AND ownership_percentage <= 100::numeric')
    op.drop_index(op.f('ix_finance_close_task_dependencies_tenant_id'), table_name='finance_close_task_dependencies')
    op.drop_table('finance_close_task_dependencies')
    op.drop_index(op.f('ix_finance_close_exceptions_tenant_id'), table_name='finance_close_exceptions')
    op.drop_index('ix_finance_close_exception_cycle_status', table_name='finance_close_exceptions')
    op.drop_table('finance_close_exceptions')
    op.drop_index('ix_finance_period_lock_tenant', table_name='finance_period_locks')
    op.drop_table('finance_period_locks')
    op.drop_index('ix_finance_close_task_tenant', table_name='finance_close_tasks')
    op.drop_index('ix_finance_close_task_cycle_status', table_name='finance_close_tasks')
    op.drop_table('finance_close_tasks')
    op.drop_index('ix_finance_close_signoff_tenant', table_name='finance_close_signoffs')
    op.drop_table('finance_close_signoffs')
    op.drop_index('ix_finance_close_audit_package_tenant', table_name='finance_close_audit_packages')
    op.drop_table('finance_close_audit_packages')
    op.drop_index(op.f('ix_finance_close_cycles_tenant_id'), table_name='finance_close_cycles')
    op.drop_index('ix_finance_close_cycle_tenant', table_name='finance_close_cycles')
    op.drop_table('finance_close_cycles')
    # ### end Alembic commands ###
