"""add financial reporting definitions runs snapshots and disclosures

Revision ID: 0013_financial_reporting
Revises: 0012_finance_close
Create Date: 2026-08-07 19:32:50.128435
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0013_financial_reporting'
down_revision: Union[str, Sequence[str], None] = '0012_finance_close'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_disclosure_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('disclosure_code', sa.String(length=100), nullable=False),
    sa.Column('disclosure_name', sa.String(length=255), nullable=False),
    sa.Column('reporting_standard', sa.Enum('IFRS', 'GAAP', 'LOCAL', name='finance_disclosure_standard'), nullable=False),
    sa.Column('standard_reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_requirements', sa.JSON(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_disclosure_definitions')),
    sa.UniqueConstraint('tenant_id', 'disclosure_code', name='uq_finance_disclosure_definition_code')
    )
    op.create_index('ix_finance_disclosure_definition_tenant', 'finance_disclosure_definitions', ['tenant_id'], unique=False)
    op.create_table('finance_report_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('report_code', sa.String(length=100), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('TRIAL_BALANCE', 'BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW', 'CHANGES_IN_EQUITY', 'BUDGET_VS_ACTUAL', 'SEGMENT_REPORT', 'CONSOLIDATED_STATEMENT', 'CFO_DASHBOARD', name='finance_report_type'), nullable=False),
    sa.Column('reporting_standard', sa.Enum('IFRS', 'GAAP', 'LOCAL', name='finance_report_standard'), nullable=False),
    sa.Column('accounting_basis', sa.Enum('ACCRUAL', 'CASH', name='finance_report_basis'), nullable=False),
    sa.Column('default_presentation', sa.Enum('SINGLE_PERIOD', 'COMPARATIVE', 'MULTI_PERIOD', 'CONSOLIDATED', name='finance_report_presentation'), nullable=False),
    sa.Column('presentation_currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_report_definitions')),
    sa.UniqueConstraint('tenant_id', 'report_code', name='uq_finance_report_definition_tenant_code')
    )
    op.create_index('ix_finance_report_definition_tenant', 'finance_report_definitions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_finance_report_definitions_tenant_id'), 'finance_report_definitions', ['tenant_id'], unique=False)
    op.create_table('finance_report_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('layout_code', sa.String(length=100), nullable=False),
    sa.Column('layout_name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['finance_report_definitions.id'], name=op.f('fk_finance_report_layouts_definition_id_finance_report_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_report_layouts')),
    sa.UniqueConstraint('definition_id', 'layout_code', name='uq_finance_report_layout_definition_code')
    )
    op.create_index('ix_finance_report_layout_tenant', 'finance_report_layouts', ['tenant_id'], unique=False)
    op.create_table('finance_report_layout_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('parent_line_id', sa.UUID(), nullable=True),
    sa.Column('line_code', sa.String(length=100), nullable=False),
    sa.Column('line_name', sa.String(length=255), nullable=False),
    sa.Column('line_type', sa.Enum('HEADER', 'ACCOUNT', 'SUBTOTAL', 'TOTAL', 'FORMULA', 'DISCLOSURE', name='finance_report_line_type'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('account_filter', sa.JSON(), nullable=True),
    sa.Column('formula_expression', sa.Text(), nullable=True),
    sa.Column('style_configuration', sa.JSON(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order')),
    sa.ForeignKeyConstraint(['layout_id'], ['finance_report_layouts.id'], name=op.f('fk_finance_report_layout_lines_layout_id_finance_report_layouts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_line_id'], ['finance_report_layout_lines.id'], name=op.f('fk_finance_report_layout_lines_parent_line_id_finance_report_layout_lines'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_report_layout_lines')),
    sa.UniqueConstraint('layout_id', 'line_code', name='uq_finance_report_layout_line_code')
    )
    op.create_index('ix_finance_report_layout_line_tenant', 'finance_report_layout_lines', ['tenant_id'], unique=False)
    op.create_table('finance_report_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('layout_id', sa.UUID(), nullable=False),
    sa.Column('run_number', sa.String(length=100), nullable=False),
    sa.Column('period_type', sa.Enum('MONTH', 'QUARTER', 'YEAR', 'CUSTOM', name='finance_report_period_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('comparative_period_start', sa.Date(), nullable=True),
    sa.Column('comparative_period_end', sa.Date(), nullable=True),
    sa.Column('presentation', sa.Enum('SINGLE_PERIOD', 'COMPARATIVE', 'MULTI_PERIOD', 'CONSOLIDATED', name='finance_report_run_presentation'), nullable=False),
    sa.Column('presentation_currency', sa.String(length=3), nullable=False),
    sa.Column('consolidation_group_id', sa.UUID(), nullable=True),
    sa.Column('budget_id', sa.UUID(), nullable=True),
    sa.Column('segment_filter', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='finance_report_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_finance_report_runs_ck_finance_report_run_valid_period')),
    sa.ForeignKeyConstraint(['budget_id'], ['finance_budgets.id'], name=op.f('fk_finance_report_runs_budget_id_finance_budgets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consolidation_group_id'], ['finance_consolidation_groups.id'], name=op.f('fk_finance_report_runs_consolidation_group_id_finance_consolidation_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['definition_id'], ['finance_report_definitions.id'], name=op.f('fk_finance_report_runs_definition_id_finance_report_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['layout_id'], ['finance_report_layouts.id'], name=op.f('fk_finance_report_runs_layout_id_finance_report_layouts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_report_runs')),
    sa.UniqueConstraint('tenant_id', 'run_number', name='uq_finance_report_run_number')
    )
    op.create_index('ix_finance_report_run_tenant_status', 'finance_report_runs', ['tenant_id', 'status'], unique=False)
    op.create_table('finance_report_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_number', sa.String(length=100), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['finance_report_runs.id'], name=op.f('fk_finance_report_snapshots_run_id_finance_report_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_report_snapshots')),
    sa.UniqueConstraint('tenant_id', 'snapshot_number', name='uq_finance_report_snapshot_number')
    )
    op.create_index('ix_finance_report_snapshot_tenant', 'finance_report_snapshots', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', 'ownership_percentage >= 0 AND ownership_percentage <= 100')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', 'voting_percentage >= 0 AND voting_percentage <= 100')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', 'amount > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', 'amount > 0::numeric')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', 'voting_percentage >= 0::numeric AND voting_percentage <= 100::numeric')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', 'ownership_percentage >= 0::numeric AND ownership_percentage <= 100::numeric')
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_index('ix_finance_report_snapshot_tenant', table_name='finance_report_snapshots')
    op.drop_table('finance_report_snapshots')
    op.drop_index('ix_finance_report_run_tenant_status', table_name='finance_report_runs')
    op.drop_table('finance_report_runs')
    op.drop_index('ix_finance_report_layout_line_tenant', table_name='finance_report_layout_lines')
    op.drop_table('finance_report_layout_lines')
    op.drop_index('ix_finance_report_layout_tenant', table_name='finance_report_layouts')
    op.drop_table('finance_report_layouts')
    op.drop_index(op.f('ix_finance_report_definitions_tenant_id'), table_name='finance_report_definitions')
    op.drop_index('ix_finance_report_definition_tenant', table_name='finance_report_definitions')
    op.drop_table('finance_report_definitions')
    op.drop_index('ix_finance_disclosure_definition_tenant', table_name='finance_disclosure_definitions')
    op.drop_table('finance_disclosure_definitions')
    # ### end Alembic commands ###
