"""add tax compliance statutory reporting and filings

Revision ID: 0014_tax_compliance
Revises: 0013_financial_reporting
Create Date: 2026-08-07 19:52:21.358356
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0014_tax_compliance'
down_revision: Union[str, Sequence[str], None] = '0013_financial_reporting'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_tax_jurisdictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_code', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=True),
    sa.Column('authority_name', sa.String(length=255), nullable=False),
    sa.Column('authority_reference', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_tax_jurisdictions')),
    sa.UniqueConstraint('tenant_id', 'jurisdiction_code', name='uq_finance_tax_jurisdiction_code')
    )
    op.create_index('ix_finance_tax_jurisdiction_tenant', 'finance_tax_jurisdictions', ['tenant_id'], unique=False)
    op.create_table('finance_tax_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('tax_code', sa.String(length=100), nullable=False),
    sa.Column('tax_name', sa.String(length=255), nullable=False),
    sa.Column('tax_type', sa.Enum('SALES_TAX', 'VAT', 'GST', 'WITHHOLDING', 'INCOME_TAX', 'EXCISE', 'CUSTOMS', 'OTHER', name='finance_tax_type'), nullable=False),
    sa.Column('input_tax_account_id', sa.UUID(), nullable=True),
    sa.Column('output_tax_account_id', sa.UUID(), nullable=True),
    sa.Column('payable_account_id', sa.UUID(), nullable=True),
    sa.Column('recoverable_account_id', sa.UUID(), nullable=True),
    sa.Column('is_recoverable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['input_tax_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_tax_codes_input_tax_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['finance_tax_jurisdictions.id'], name=op.f('fk_finance_tax_codes_jurisdiction_id_finance_tax_jurisdictions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['output_tax_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_tax_codes_output_tax_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['payable_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_tax_codes_payable_account_id_finance_ledger_accounts')),
    sa.ForeignKeyConstraint(['recoverable_account_id'], ['finance_ledger_accounts.id'], name=op.f('fk_finance_tax_codes_recoverable_account_id_finance_ledger_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_tax_codes')),
    sa.UniqueConstraint('tenant_id', 'tax_code', name='uq_finance_tax_code')
    )
    op.create_index('ix_finance_tax_code_tenant', 'finance_tax_codes', ['tenant_id'], unique=False)
    op.create_table('finance_tax_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=150), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['finance_tax_jurisdictions.id'], name=op.f('fk_finance_tax_registrations_jurisdiction_id_finance_tax_jurisdictions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_tax_registrations')),
    sa.UniqueConstraint('tenant_id', 'registration_number', name='uq_finance_tax_registration_number')
    )
    op.create_index('ix_finance_tax_registration_tenant', 'finance_tax_registrations', ['tenant_id'], unique=False)
    op.create_table('finance_withholding_tax_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('jurisdiction_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('threshold_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rate >= 0 AND rate <= 100', name=op.f('ck_finance_withholding_tax_rules_ck_finance_withholding_rate')),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['finance_tax_jurisdictions.id'], name=op.f('fk_finance_withholding_tax_rules_jurisdiction_id_finance_tax_jurisdictions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_withholding_tax_rules')),
    sa.UniqueConstraint('tenant_id', 'rule_code', name='uq_finance_withholding_rule_code')
    )
    op.create_index(op.f('ix_finance_withholding_tax_rules_tenant_id'), 'finance_withholding_tax_rules', ['tenant_id'], unique=False)
    op.create_table('finance_tax_periods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('registration_id', sa.UUID(), nullable=False),
    sa.Column('period_name', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filing_due_date', sa.Date(), nullable=False),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_finance_tax_periods_ck_finance_tax_period_range')),
    sa.ForeignKeyConstraint(['registration_id'], ['finance_tax_registrations.id'], name=op.f('fk_finance_tax_periods_registration_id_finance_tax_registrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_tax_periods')),
    sa.UniqueConstraint('registration_id', 'period_start', 'period_end', name='uq_finance_tax_period_range')
    )
    op.create_index(op.f('ix_finance_tax_periods_tenant_id'), 'finance_tax_periods', ['tenant_id'], unique=False)
    op.create_table('finance_tax_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tax_code_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.CheckConstraint('rate >= 0 AND rate <= 100', name=op.f('ck_finance_tax_rates_ck_finance_tax_rate_percentage')),
    sa.ForeignKeyConstraint(['tax_code_id'], ['finance_tax_codes.id'], name=op.f('fk_finance_tax_rates_tax_code_id_finance_tax_codes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_tax_rates')),
    sa.UniqueConstraint('tax_code_id', 'effective_from', name='uq_finance_tax_rate_effective_date')
    )
    op.create_index('ix_finance_tax_rate_tenant', 'finance_tax_rates', ['tenant_id'], unique=False)
    op.create_table('finance_tax_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tax_period_id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PREPARED', 'REVIEWED', 'FILED', 'ACCEPTED', 'REJECTED', 'AMENDED', 'CANCELLED', name='finance_tax_return_status'), nullable=False),
    sa.Column('output_tax', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('input_tax', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('withholding_tax', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('adjustments', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('credits', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('net_tax_liability', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('prepared_by', sa.UUID(), nullable=False),
    sa.Column('filed_by', sa.UUID(), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authority_reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tax_period_id'], ['finance_tax_periods.id'], name=op.f('fk_finance_tax_returns_tax_period_id_finance_tax_periods'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_tax_returns')),
    sa.UniqueConstraint('tenant_id', 'return_number', name='uq_finance_tax_return_number')
    )
    op.create_index('ix_finance_tax_return_tenant_status', 'finance_tax_returns', ['tenant_id', 'status'], unique=False)
    op.create_table('finance_statutory_filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tax_return_id', sa.UUID(), nullable=True),
    sa.Column('filing_number', sa.String(length=100), nullable=False),
    sa.Column('filing_type', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'OVERDUE', name='finance_statutory_filing_status'), nullable=False),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('submission_reference', sa.String(length=255), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tax_return_id'], ['finance_tax_returns.id'], name=op.f('fk_finance_statutory_filings_tax_return_id_finance_tax_returns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_statutory_filings')),
    sa.UniqueConstraint('tenant_id', 'filing_number', name='uq_finance_statutory_filing_number')
    )
    op.create_index('ix_finance_statutory_filing_tenant_status', 'finance_statutory_filings', ['tenant_id', 'status'], unique=False)
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', 'ownership_percentage >= 0 AND ownership_percentage <= 100')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', 'voting_percentage >= 0 AND voting_percentage <= 100')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', 'amount > 0')
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', 'display_order >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', 'display_order >= 0')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', 'amount > 0::numeric')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', 'voting_percentage >= 0::numeric AND voting_percentage <= 100::numeric')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', 'ownership_percentage >= 0::numeric AND ownership_percentage <= 100::numeric')
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_index('ix_finance_statutory_filing_tenant_status', table_name='finance_statutory_filings')
    op.drop_table('finance_statutory_filings')
    op.drop_index('ix_finance_tax_return_tenant_status', table_name='finance_tax_returns')
    op.drop_table('finance_tax_returns')
    op.drop_index('ix_finance_tax_rate_tenant', table_name='finance_tax_rates')
    op.drop_table('finance_tax_rates')
    op.drop_index(op.f('ix_finance_tax_periods_tenant_id'), table_name='finance_tax_periods')
    op.drop_table('finance_tax_periods')
    op.drop_index(op.f('ix_finance_withholding_tax_rules_tenant_id'), table_name='finance_withholding_tax_rules')
    op.drop_table('finance_withholding_tax_rules')
    op.drop_index('ix_finance_tax_registration_tenant', table_name='finance_tax_registrations')
    op.drop_table('finance_tax_registrations')
    op.drop_index('ix_finance_tax_code_tenant', table_name='finance_tax_codes')
    op.drop_table('finance_tax_codes')
    op.drop_index('ix_finance_tax_jurisdiction_tenant', table_name='finance_tax_jurisdictions')
    op.drop_table('finance_tax_jurisdictions')
    # ### end Alembic commands ###
