"""add islamic finance zakat ushr sadaqah and shariah governance

Revision ID: 0015_islamic_finance
Revises: 0014_tax_compliance
Create Date: 2026-08-07 20:09:00.086395
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0015_islamic_finance'
down_revision: Union[str, Sequence[str], None] = '0014_tax_compliance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_islamic_disbursement_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assessment_type', sa.Enum('MONETARY_ZAKAT', 'LIVESTOCK_ZAKAT', 'CROP_USHR', 'SADAQAH', name='finance_islamic_assessment_type'), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('evidence_number', sa.String(length=100), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('beneficiary_reference', sa.String(length=255), nullable=True),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_islamic_disbursement_evidence')),
    sa.UniqueConstraint('tenant_id', 'evidence_number', name='uq_finance_islamic_disbursement_evidence')
    )
    op.create_index(op.f('ix_finance_islamic_disbursement_evidence_tenant_id'), 'finance_islamic_disbursement_evidence', ['tenant_id'], unique=False)
    op.create_table('finance_sadaqah_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_number', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('beneficiary_reference', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_sadaqah_transactions')),
    sa.UniqueConstraint('tenant_id', 'transaction_number', name='uq_finance_sadaqah_transaction_number')
    )
    op.create_index(op.f('ix_finance_sadaqah_transactions_tenant_id'), 'finance_sadaqah_transactions', ['tenant_id'], unique=False)
    op.create_table('finance_shariah_rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'APPROVED', 'RETIRED', name='finance_islamic_rule_status'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('shariah_reference', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_shariah_rule_sets')),
    sa.UniqueConstraint('tenant_id', 'rule_code', 'version_number', name='uq_finance_shariah_rule_version')
    )
    op.create_index('ix_finance_shariah_rule_tenant', 'finance_shariah_rule_sets', ['tenant_id'], unique=False)
    op.create_table('finance_livestock_zakat_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('species_code', sa.String(length=100), nullable=False),
    sa.Column('minimum_count', sa.Integer(), nullable=False),
    sa.Column('maximum_count', sa.Integer(), nullable=True),
    sa.Column('obligation_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('obligation_unit', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('maximum_count IS NULL OR maximum_count >= minimum_count', name=op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_zakat_count_range')),
    sa.ForeignKeyConstraint(['rule_set_id'], ['finance_shariah_rule_sets.id'], name=op.f('fk_finance_livestock_zakat_rules_rule_set_id_finance_shariah_rule_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_livestock_zakat_rules')),
    sa.UniqueConstraint('rule_set_id', 'species_code', 'minimum_count', name='uq_finance_livestock_zakat_rule')
    )
    op.create_index(op.f('ix_finance_livestock_zakat_rules_tenant_id'), 'finance_livestock_zakat_rules', ['tenant_id'], unique=False)
    op.create_table('finance_nisab_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('nisab_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['finance_shariah_rule_sets.id'], name=op.f('fk_finance_nisab_references_rule_set_id_finance_shariah_rule_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_nisab_references')),
    sa.UniqueConstraint('tenant_id', 'rule_set_id', 'reference_date', name='uq_finance_nisab_reference_date')
    )
    op.create_index('ix_finance_nisab_reference_tenant', 'finance_nisab_references', ['tenant_id'], unique=False)
    op.create_table('finance_ushr_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('assessment_number', sa.String(length=100), nullable=False),
    sa.Column('crop_batch_reference', sa.String(length=200), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('irrigation_method', sa.String(length=100), nullable=False),
    sa.Column('eligible_output_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('ushr_due', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'REVIEWED', 'APPROVED', 'PAID', 'CANCELLED', name='finance_ushr_assessment_status'), nullable=False),
    sa.Column('prepared_by', sa.UUID(), nullable=False),
    sa.CheckConstraint('rate_percentage >= 0 AND rate_percentage <= 100', name=op.f('ck_finance_ushr_assessments_ck_finance_ushr_rate')),
    sa.ForeignKeyConstraint(['rule_set_id'], ['finance_shariah_rule_sets.id'], name=op.f('fk_finance_ushr_assessments_rule_set_id_finance_shariah_rule_sets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_ushr_assessments')),
    sa.UniqueConstraint('tenant_id', 'assessment_number', name='uq_finance_ushr_assessment_number')
    )
    op.create_index(op.f('ix_finance_ushr_assessments_tenant_id'), 'finance_ushr_assessments', ['tenant_id'], unique=False)
    op.create_table('finance_zakat_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('nisab_reference_id', sa.UUID(), nullable=True),
    sa.Column('assessment_number', sa.String(length=100), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('eligible_assets', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('deductible_liabilities', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('zakatable_base', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('nisab_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('rate_percentage', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('holding_days', sa.Integer(), nullable=False),
    sa.Column('required_hawl_days', sa.Integer(), nullable=False),
    sa.Column('zakat_due', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'REVIEWED', 'APPROVED', 'PAID', 'CANCELLED', name='finance_islamic_assessment_status'), nullable=False),
    sa.Column('prepared_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nisab_reference_id'], ['finance_nisab_references.id'], name=op.f('fk_finance_zakat_assessments_nisab_reference_id_finance_nisab_references'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['finance_shariah_rule_sets.id'], name=op.f('fk_finance_zakat_assessments_rule_set_id_finance_shariah_rule_sets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_zakat_assessments')),
    sa.UniqueConstraint('tenant_id', 'assessment_number', name='uq_finance_zakat_assessment_number')
    )
    op.create_index('ix_finance_zakat_assessment_tenant_status', 'finance_zakat_assessments', ['tenant_id', 'status'], unique=False)
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', 'ownership_percentage >= 0 AND ownership_percentage <= 100')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', 'voting_percentage >= 0 AND voting_percentage <= 100')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', 'amount > 0')
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', 'display_order >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', 'display_order >= 0')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', 'amount > 0::numeric')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', 'voting_percentage >= 0::numeric AND voting_percentage <= 100::numeric')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', 'ownership_percentage >= 0::numeric AND ownership_percentage <= 100::numeric')
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_index('ix_finance_zakat_assessment_tenant_status', table_name='finance_zakat_assessments')
    op.drop_table('finance_zakat_assessments')
    op.drop_index(op.f('ix_finance_ushr_assessments_tenant_id'), table_name='finance_ushr_assessments')
    op.drop_table('finance_ushr_assessments')
    op.drop_index('ix_finance_nisab_reference_tenant', table_name='finance_nisab_references')
    op.drop_table('finance_nisab_references')
    op.drop_index(op.f('ix_finance_livestock_zakat_rules_tenant_id'), table_name='finance_livestock_zakat_rules')
    op.drop_table('finance_livestock_zakat_rules')
    op.drop_index('ix_finance_shariah_rule_tenant', table_name='finance_shariah_rule_sets')
    op.drop_table('finance_shariah_rule_sets')
    op.drop_index(op.f('ix_finance_sadaqah_transactions_tenant_id'), table_name='finance_sadaqah_transactions')
    op.drop_table('finance_sadaqah_transactions')
    op.drop_index(op.f('ix_finance_islamic_disbursement_evidence_tenant_id'), table_name='finance_islamic_disbursement_evidence')
    op.drop_table('finance_islamic_disbursement_evidence')
    # ### end Alembic commands ###
