"""add finance controls reconciliation audit and governance

Revision ID: 0016_finance_controls
Revises: 0015_islamic_finance
Create Date: 2026-08-08 12:19:05.072461
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0016_finance_controls'
down_revision: Union[str, Sequence[str], None] = '0015_islamic_finance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_control_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('control_code', sa.String(length=100), nullable=False),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('control_type', sa.Enum('PREVENTIVE', 'DETECTIVE', 'CORRECTIVE', 'GOVERNANCE', name='finance_control_type'), nullable=False),
    sa.Column('frequency', sa.Enum('TRANSACTION', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'EVENT_DRIVEN', name='finance_control_frequency'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'RETIRED', name='finance_control_status'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('risk_statement', sa.Text(), nullable=False),
    sa.Column('control_objective', sa.Text(), nullable=False),
    sa.Column('procedure_description', sa.Text(), nullable=False),
    sa.Column('is_key_control', sa.Boolean(), nullable=False),
    sa.Column('inherent_risk_score', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_control_definitions')),
    sa.UniqueConstraint('tenant_id', 'control_code', name='uq_finance_control_definition_code')
    )
    op.create_index('ix_finance_control_definition_tenant', 'finance_control_definitions', ['tenant_id'], unique=False)
    op.create_table('finance_reconciliation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_number', sa.String(length=100), nullable=False),
    sa.Column('reconciliation_type', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('target_reference', sa.String(length=255), nullable=False),
    sa.Column('source_balance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('target_balance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('variance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'MATCHED', 'UNMATCHED', 'REVIEWED', 'CLOSED', name='finance_control_reconciliation_status'), nullable=False),
    sa.Column('prepared_by', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_reconciliation_runs')),
    sa.UniqueConstraint('tenant_id', 'reconciliation_number', name='uq_finance_reconciliation_number')
    )
    op.create_index('ix_finance_reconciliation_tenant_status', 'finance_reconciliation_runs', ['tenant_id', 'status'], unique=False)
    op.create_table('finance_sod_violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('violation_number', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('conflicting_action_a', sa.String(length=255), nullable=False),
    sa.Column('conflicting_action_b', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finance_control_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'REMEDIATED', 'WAIVED', 'CLOSED', name='finance_sod_violation_status'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remediated_by', sa.UUID(), nullable=True),
    sa.Column('remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediation_notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_sod_violations')),
    sa.UniqueConstraint('tenant_id', 'violation_number', name='uq_finance_sod_violation_number')
    )
    op.create_index('ix_finance_sod_violation_tenant_status', 'finance_sod_violations', ['tenant_id', 'status'], unique=False)
    op.create_table('finance_control_attestations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('attestation_number', sa.String(length=100), nullable=False),
    sa.Column('attestation_period', sa.String(length=100), nullable=False),
    sa.Column('attestor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ATTESTED', 'REJECTED', 'EXPIRED', name='finance_control_attestation_status'), nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['finance_control_definitions.id'], name=op.f('fk_finance_control_attestations_control_id_finance_control_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_control_attestations')),
    sa.UniqueConstraint('tenant_id', 'attestation_number', name='uq_finance_control_attestation_number')
    )
    op.create_index('ix_finance_control_attestation_tenant', 'finance_control_attestations', ['tenant_id'], unique=False)
    op.create_table('finance_control_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('execution_number', sa.String(length=100), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'EXCEPTION', 'WAIVED', name='finance_control_execution_status'), nullable=False),
    sa.Column('tested_population', sa.Integer(), nullable=False),
    sa.Column('passed_checks', sa.Integer(), nullable=False),
    sa.Column('failed_checks', sa.Integer(), nullable=False),
    sa.Column('effectiveness_percentage', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('residual_risk_score', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('executed_by', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['finance_control_definitions.id'], name=op.f('fk_finance_control_executions_control_id_finance_control_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_control_executions')),
    sa.UniqueConstraint('tenant_id', 'execution_number', name='uq_finance_control_execution_number')
    )
    op.create_index('ix_finance_control_execution_control_status', 'finance_control_executions', ['control_id', 'status'], unique=False)
    op.create_index(op.f('ix_finance_control_executions_tenant_id'), 'finance_control_executions', ['tenant_id'], unique=False)
    op.create_table('finance_audit_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('evidence_number', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['finance_control_definitions.id'], name=op.f('fk_finance_audit_evidence_control_id_finance_control_definitions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['finance_control_executions.id'], name=op.f('fk_finance_audit_evidence_execution_id_finance_control_executions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_audit_evidence')),
    sa.UniqueConstraint('tenant_id', 'evidence_number', name='uq_finance_audit_evidence_number')
    )
    op.create_index('ix_finance_audit_evidence_tenant', 'finance_audit_evidence', ['tenant_id'], unique=False)
    op.create_table('finance_control_exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('reconciliation_id', sa.UUID(), nullable=True),
    sa.Column('exception_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='finance_control_exception_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'REMEDIATED', 'WAIVED', 'CLOSED', name='finance_control_exception_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('remediation_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['finance_control_executions.id'], name=op.f('fk_finance_control_exceptions_execution_id_finance_control_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['finance_reconciliation_runs.id'], name=op.f('fk_finance_control_exceptions_reconciliation_id_finance_reconciliation_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_control_exceptions')),
    sa.UniqueConstraint('tenant_id', 'exception_number', name='uq_finance_control_exception_number')
    )
    op.create_index('ix_finance_control_exception_tenant_status', 'finance_control_exceptions', ['tenant_id', 'status'], unique=False)
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', 'ownership_percentage >= 0 AND ownership_percentage <= 100')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', 'voting_percentage >= 0 AND voting_percentage <= 100')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', 'amount > 0')
    op.drop_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_z_c87e'), 'finance_livestock_zakat_rules', type_='check')
    op.create_check_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_zakat_count_range'), 'finance_livestock_zakat_rules', 'maximum_count IS NULL OR maximum_count >= minimum_count')
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', 'display_order >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', 'display_order >= 0')
    op.drop_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_zakat_count_range'), 'finance_livestock_zakat_rules', type_='check')
    op.create_check_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_z_c87e'), 'finance_livestock_zakat_rules', 'maximum_count IS NULL OR maximum_count >= minimum_count')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', 'amount > 0::numeric')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', 'voting_percentage >= 0::numeric AND voting_percentage <= 100::numeric')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', 'ownership_percentage >= 0::numeric AND ownership_percentage <= 100::numeric')
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_index('ix_finance_control_exception_tenant_status', table_name='finance_control_exceptions')
    op.drop_table('finance_control_exceptions')
    op.drop_index('ix_finance_audit_evidence_tenant', table_name='finance_audit_evidence')
    op.drop_table('finance_audit_evidence')
    op.drop_index(op.f('ix_finance_control_executions_tenant_id'), table_name='finance_control_executions')
    op.drop_index('ix_finance_control_execution_control_status', table_name='finance_control_executions')
    op.drop_table('finance_control_executions')
    op.drop_index('ix_finance_control_attestation_tenant', table_name='finance_control_attestations')
    op.drop_table('finance_control_attestations')
    op.drop_index('ix_finance_sod_violation_tenant_status', table_name='finance_sod_violations')
    op.drop_table('finance_sod_violations')
    op.drop_index('ix_finance_reconciliation_tenant_status', table_name='finance_reconciliation_runs')
    op.drop_table('finance_reconciliation_runs')
    op.drop_index('ix_finance_control_definition_tenant', table_name='finance_control_definitions')
    op.drop_table('finance_control_definitions')
    # ### end Alembic commands ###
