"""add finance analytics kpi snapshots and cfo dashboard

Revision ID: 0017_finance_analytics
Revises: 0016_finance_controls
Create Date: 2026-08-08 13:32:40.175985
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0017_finance_analytics'
down_revision: Union[str, Sequence[str], None] = '0016_finance_controls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_analytics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_number', sa.String(length=64), nullable=False),
    sa.Column('period_type', sa.Enum('DAILY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='finance_analytics_period_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('cost_of_goods_sold', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('operating_income', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('net_income', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('current_assets', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('current_liabilities', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('accounts_receivable', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('accounts_payable', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('inventory', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('operating_cash_flow', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('capital_expenditure', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('current_ratio', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('gross_margin_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('operating_margin_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('net_margin_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('ebitda_margin_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_on_assets_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('return_on_equity_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('debt_to_equity_ratio', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('dso_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dpo_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inventory_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_conversion_cycle_days', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('free_cash_flow', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('budget_utilization_percentage', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'APPROVED', 'SUPERSEDED', name='finance_analytics_snapshot_status'), nullable=False),
    sa.Column('calculated_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finance_analytics_snapshots')),
    sa.UniqueConstraint('tenant_id', 'period_type', 'period_start', 'period_end', 'currency_code', name='uq_finance_analytics_snapshot_period'),
    sa.UniqueConstraint('tenant_id', 'snapshot_number', name='uq_finance_analytics_snapshot_number')
    )
    op.create_index('ix_finance_analytics_snapshot_tenant_period', 'finance_analytics_snapshots', ['tenant_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_finance_analytics_snapshot_tenant_status', 'finance_analytics_snapshots', ['tenant_id', 'status'], unique=False)
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', 'ownership_percentage >= 0 AND ownership_percentage <= 100')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', 'voting_percentage >= 0 AND voting_percentage <= 100')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', 'amount > 0')
    op.drop_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_z_c87e'), 'finance_livestock_zakat_rules', type_='check')
    op.create_check_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_zakat_count_range'), 'finance_livestock_zakat_rules', 'maximum_count IS NULL OR maximum_count >= minimum_count')
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', 'display_order >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_line_display_order'), 'finance_report_layout_lines', type_='check')
    op.create_check_constraint(op.f('ck_finance_report_layout_lines_ck_finance_report_layout_9636'), 'finance_report_layout_lines', 'display_order >= 0')
    op.drop_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_zakat_count_range'), 'finance_livestock_zakat_rules', type_='check')
    op.create_check_constraint(op.f('ck_finance_livestock_zakat_rules_ck_finance_livestock_z_c87e'), 'finance_livestock_zakat_rules', 'maximum_count IS NULL OR maximum_count >= minimum_count')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_positive_amount'), 'finance_intercompany_transactions', type_='check')
    op.drop_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_transaction_distinct_companies'), 'finance_intercompany_transactions', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_44a1'), 'finance_intercompany_transactions', 'source_organization_id <> destination_organization_id')
    op.create_check_constraint(op.f('ck_finance_intercompany_transactions_ck_intercompany_tr_42db'), 'finance_intercompany_transactions', 'amount > 0::numeric')
    op.drop_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account_mapping_distinct_companies'), 'finance_intercompany_account_mappings', type_='check')
    op.create_check_constraint(op.f('ck_finance_intercompany_account_mappings_ck_ic_account__30fc'), 'finance_intercompany_account_mappings', 'source_organization_id <> destination_organization_id')
    op.drop_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_period_valid_range'), 'finance_consolidation_periods', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_periods_ck_consolidation_perio_9efd'), 'finance_consolidation_periods', 'period_end >= period_start')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_voting_percentage'), 'finance_consolidation_group_members', type_='check')
    op.drop_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_member_ownership_percentage'), 'finance_consolidation_group_members', type_='check')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_7255'), 'finance_consolidation_group_members', 'voting_percentage >= 0::numeric AND voting_percentage <= 100::numeric')
    op.create_check_constraint(op.f('ck_finance_consolidation_group_members_ck_consolidation_0819'), 'finance_consolidation_group_members', 'ownership_percentage >= 0::numeric AND ownership_percentage <= 100::numeric')
    op.drop_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_task_no_self_dependency'), 'finance_close_task_dependencies', type_='check')
    op.create_check_constraint(op.f('ck_finance_close_task_dependencies_ck_finance_close_tas_5868'), 'finance_close_task_dependencies', 'task_id <> depends_on_task_id')
    op.drop_index('ix_finance_analytics_snapshot_tenant_status', table_name='finance_analytics_snapshots')
    op.drop_index('ix_finance_analytics_snapshot_tenant_period', table_name='finance_analytics_snapshots')
    op.drop_table('finance_analytics_snapshots')
    # ### end Alembic commands ###
