"""add goods receipt domain

Revision ID: 090669936e69
Revises: 78962f3c0110
Create Date: 2026-08-08 23:00:13.771414
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '090669936e69'
down_revision: Union[str, Sequence[str], None] = '78962f3c0110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_goods_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=True, comment='Reference to Warehouse service.'),
    sa.Column('delivery_note_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RECEIVED', 'UNDER_INSPECTION', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', 'CANCELLED', name='procurement_goods_receipt_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['procurement_purchase_orders.id'], name=op.f('fk_procurement_goods_receipts_purchase_order_id_procurement_purchase_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], name=op.f('fk_procurement_goods_receipts_supplier_id_procurement_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_goods_receipts')),
    sa.UniqueConstraint('tenant_id', 'receipt_number', name='uq_procurement_goods_receipt_number')
    )
    op.create_index(op.f('ix_procurement_goods_receipts_tenant_id'), 'procurement_goods_receipts', ['tenant_id'], unique=False)
    op.create_index('ix_procurement_receipt_tenant_po', 'procurement_goods_receipts', ['tenant_id', 'purchase_order_id'], unique=False)
    op.create_index('ix_procurement_receipt_tenant_status', 'procurement_goods_receipts', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_procurement_receipt_tenant_supplier', 'procurement_goods_receipts', ['tenant_id', 'supplier_id'], unique=False)
    op.create_table('procurement_goods_receipt_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True, comment='Reference to Inventory item master.'),
    sa.Column('warehouse_location_id', sa.UUID(), nullable=True, comment='Reference to Warehouse storage location.'),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('accepted_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('rejected_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('inspection_status', sa.Enum('NOT_REQUIRED', 'PENDING', 'PASSED', 'PARTIALLY_PASSED', 'FAILED', name='procurement_receipt_inspection_status'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'ACCEPTED', 'PARTIALLY_ACCEPTED', 'REJECTED', name='procurement_goods_receipt_line_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('accepted_quantity + rejected_quantity <= received_quantity', name=op.f('ck_procurement_goods_receipt_lines_receipt_disposition_valid')),
    sa.CheckConstraint('accepted_quantity >= 0', name=op.f('ck_procurement_goods_receipt_lines_receipt_accept_nonnegative')),
    sa.CheckConstraint('received_quantity > 0', name=op.f('ck_procurement_goods_receipt_lines_receipt_qty_positive')),
    sa.CheckConstraint('rejected_quantity >= 0', name=op.f('ck_procurement_goods_receipt_lines_receipt_reject_nonnegative')),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['procurement_goods_receipts.id'], name=op.f('fk_procurement_goods_receipt_lines_goods_receipt_id_procurement_goods_receipts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['procurement_purchase_order_lines.id'], name=op.f('fk_procurement_goods_receipt_lines_purchase_order_line_id_procurement_purchase_order_lines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_goods_receipt_lines')),
    sa.UniqueConstraint('goods_receipt_id', 'line_number', name='uq_procurement_receipt_line_number')
    )
    op.create_index(op.f('ix_procurement_goods_receipt_lines_tenant_id'), 'procurement_goods_receipt_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_goods_receipt_lines_tenant_id'), table_name='procurement_goods_receipt_lines')
    op.drop_table('procurement_goods_receipt_lines')
    op.drop_index('ix_procurement_receipt_tenant_supplier', table_name='procurement_goods_receipts')
    op.drop_index('ix_procurement_receipt_tenant_status', table_name='procurement_goods_receipts')
    op.drop_index('ix_procurement_receipt_tenant_po', table_name='procurement_goods_receipts')
    op.drop_index(op.f('ix_procurement_goods_receipts_tenant_id'), table_name='procurement_goods_receipts')
    op.drop_table('procurement_goods_receipts')

    # GOODS_RECEIPT_ENUM_CLEANUP
    sa.Enum(
        name='procurement_goods_receipt_line_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_receipt_inspection_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_goods_receipt_status',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
