"""add supplier and purchase requisition domain

Revision ID: 326e896819b9
Revises: 0001_procurement_foundation
Create Date: 2026-08-08 21:01:33.371198
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '326e896819b9'
down_revision: Union[str, Sequence[str], None] = '0001_procurement_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_purchase_requisitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('requisition_number', sa.String(length=100), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('cost_centre_id', sa.UUID(), nullable=True, comment='Reference to Finance cost centre.'),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('required_by_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='procurement_requisition_priority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PARTIALLY_SOURCED', 'FULLY_SOURCED', 'CANCELLED', name='procurement_requisition_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_purchase_requisitions')),
    sa.UniqueConstraint('tenant_id', 'requisition_number', name='uq_procurement_requisition_number')
    )
    op.create_index(op.f('ix_procurement_purchase_requisitions_tenant_id'), 'procurement_purchase_requisitions', ['tenant_id'], unique=False)
    op.create_index('ix_procurement_requisition_required_date', 'procurement_purchase_requisitions', ['tenant_id', 'required_by_date'], unique=False)
    op.create_index('ix_procurement_requisition_tenant_status', 'procurement_purchase_requisitions', ['tenant_id', 'status'], unique=False)
    op.create_table('procurement_suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('finance_vendor_id', sa.UUID(), nullable=True, comment='Reference to Finance vendor representation; not a database FK across service ownership.'),
    sa.Column('tax_identifier', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUSPENDED', 'BLOCKED', 'INACTIVE', name='procurement_supplier_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_suppliers')),
    sa.UniqueConstraint('tenant_id', 'supplier_code', name='uq_procurement_supplier_code')
    )
    op.create_index('ix_procurement_supplier_tenant_status', 'procurement_suppliers', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_suppliers_tenant_id'), 'procurement_suppliers', ['tenant_id'], unique=False)
    op.create_table('procurement_purchase_requisition_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True, comment='Reference to future Inventory item master.'),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('preferred_supplier_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('estimated_unit_price >= 0', name=op.f('ck_procurement_purchase_requisition_lines_price_nonnegative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_procurement_purchase_requisition_lines_qty_positive')),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['procurement_suppliers.id'], name=op.f('fk_procurement_purchase_requisition_lines_preferred_supplier_id_procurement_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisition_id'], ['procurement_purchase_requisitions.id'], name=op.f('fk_procurement_purchase_requisition_lines_requisition_id_procurement_purchase_requisitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_purchase_requisition_lines')),
    sa.UniqueConstraint('requisition_id', 'line_number', name='uq_procurement_requisition_line_number')
    )
    op.create_index(op.f('ix_procurement_purchase_requisition_lines_tenant_id'), 'procurement_purchase_requisition_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_purchase_requisition_lines_tenant_id'), table_name='procurement_purchase_requisition_lines')
    op.drop_table('procurement_purchase_requisition_lines')
    op.drop_index(op.f('ix_procurement_suppliers_tenant_id'), table_name='procurement_suppliers')
    op.drop_index('ix_procurement_supplier_tenant_status', table_name='procurement_suppliers')
    op.drop_table('procurement_suppliers')
    op.drop_index('ix_procurement_requisition_tenant_status', table_name='procurement_purchase_requisitions')
    op.drop_index('ix_procurement_requisition_required_date', table_name='procurement_purchase_requisitions')
    op.drop_index(op.f('ix_procurement_purchase_requisitions_tenant_id'), table_name='procurement_purchase_requisitions')
    op.drop_table('procurement_purchase_requisitions')

    sa.Enum(
        name='procurement_supplier_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_requisition_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_requisition_priority',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
