"""add purchase order domain

Revision ID: 78962f3c0110
Revises: 823ffc0e914a
Create Date: 2026-08-08 22:08:55.530816
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '78962f3c0110'
down_revision: Union[str, Sequence[str], None] = '823ffc0e914a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('source_quotation_id', sa.UUID(), nullable=True),
    sa.Column('requisition_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('delivery_location', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ISSUED', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CLOSED', 'CANCELLED', name='procurement_purchase_order_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_procurement_purchase_orders_po_discount_nonnegative')),
    sa.CheckConstraint('subtotal_amount >= 0', name=op.f('ck_procurement_purchase_orders_po_subtotal_nonnegative')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_procurement_purchase_orders_po_tax_nonnegative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_procurement_purchase_orders_po_total_nonnegative')),
    sa.ForeignKeyConstraint(['requisition_id'], ['procurement_purchase_requisitions.id'], name=op.f('fk_procurement_purchase_orders_requisition_id_procurement_purchase_requisitions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_quotation_id'], ['procurement_supplier_quotations.id'], name=op.f('fk_procurement_purchase_orders_source_quotation_id_procurement_supplier_quotations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], name=op.f('fk_procurement_purchase_orders_supplier_id_procurement_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_purchase_orders')),
    sa.UniqueConstraint('tenant_id', 'po_number', name='uq_procurement_po_number')
    )
    op.create_index('ix_procurement_po_tenant_status', 'procurement_purchase_orders', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_procurement_po_tenant_supplier', 'procurement_purchase_orders', ['tenant_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_procurement_purchase_orders_tenant_id'), 'procurement_purchase_orders', ['tenant_id'], unique=False)
    op.create_table('procurement_purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('requisition_line_id', sa.UUID(), nullable=True),
    sa.Column('quotation_line_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True, comment='Reference to Inventory item master.'),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED', name='procurement_purchase_order_line_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_procurement_purchase_order_lines_po_line_disc_nonneg')),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_procurement_purchase_order_lines_po_line_total_nonnegative')),
    sa.CheckConstraint('ordered_quantity > 0', name=op.f('ck_procurement_purchase_order_lines_po_line_qty_positive')),
    sa.CheckConstraint('tax_amount >= 0', name=op.f('ck_procurement_purchase_order_lines_po_line_tax_nonnegative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_procurement_purchase_order_lines_po_line_price_nonnegative')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['procurement_purchase_orders.id'], name=op.f('fk_procurement_purchase_order_lines_purchase_order_id_procurement_purchase_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['procurement_supplier_quotation_lines.id'], name=op.f('fk_procurement_purchase_order_lines_quotation_line_id_procurement_supplier_quotation_lines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisition_line_id'], ['procurement_purchase_requisition_lines.id'], name=op.f('fk_procurement_purchase_order_lines_requisition_line_id_procurement_purchase_requisition_lines'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_purchase_order_lines')),
    sa.UniqueConstraint('purchase_order_id', 'line_number', name='uq_procurement_po_line_number')
    )
    op.create_index(op.f('ix_procurement_purchase_order_lines_tenant_id'), 'procurement_purchase_order_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_purchase_order_lines_tenant_id'), table_name='procurement_purchase_order_lines')
    op.drop_table('procurement_purchase_order_lines')
    op.drop_index(op.f('ix_procurement_purchase_orders_tenant_id'), table_name='procurement_purchase_orders')
    op.drop_index('ix_procurement_po_tenant_supplier', table_name='procurement_purchase_orders')
    op.drop_index('ix_procurement_po_tenant_status', table_name='procurement_purchase_orders')
    op.drop_table('procurement_purchase_orders')

    sa.Enum(
        name='procurement_purchase_order_line_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_purchase_order_status',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
