"""add rfq and supplier quotation domain

Revision ID: 823ffc0e914a
Revises: 326e896819b9
Create Date: 2026-08-08 21:39:20.614299
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '823ffc0e914a'
down_revision: Union[str, Sequence[str], None] = '326e896819b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_rfqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rfq_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requisition_id', sa.UUID(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('closing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'CLOSED', 'CANCELLED', 'AWARDED', name='procurement_rfq_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['procurement_purchase_requisitions.id'], name=op.f('fk_procurement_rfqs_requisition_id_procurement_purchase_requisitions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_rfqs')),
    sa.UniqueConstraint('tenant_id', 'rfq_number', name='uq_procurement_rfq_number')
    )
    op.create_index('ix_procurement_rfq_tenant_closing', 'procurement_rfqs', ['tenant_id', 'closing_at'], unique=False)
    op.create_index('ix_procurement_rfq_tenant_status', 'procurement_rfqs', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_rfqs_tenant_id'), 'procurement_rfqs', ['tenant_id'], unique=False)
    op.create_table('procurement_rfq_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('requisition_line_id', sa.UUID(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_procurement_rfq_lines_rfq_qty_positive')),
    sa.ForeignKeyConstraint(['requisition_line_id'], ['procurement_purchase_requisition_lines.id'], name=op.f('fk_procurement_rfq_lines_requisition_line_id_procurement_purchase_requisition_lines'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfq_id'], ['procurement_rfqs.id'], name=op.f('fk_procurement_rfq_lines_rfq_id_procurement_rfqs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_rfq_lines')),
    sa.UniqueConstraint('rfq_id', 'line_number', name='uq_procurement_rfq_line_number')
    )
    op.create_index(op.f('ix_procurement_rfq_lines_tenant_id'), 'procurement_rfq_lines', ['tenant_id'], unique=False)
    op.create_table('procurement_supplier_quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('quotation_number', sa.String(length=100), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_EVALUATION', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='procurement_quotation_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['procurement_rfqs.id'], name=op.f('fk_procurement_supplier_quotations_rfq_id_procurement_rfqs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], name=op.f('fk_procurement_supplier_quotations_supplier_id_procurement_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_supplier_quotations')),
    sa.UniqueConstraint('rfq_id', 'supplier_id', name='uq_procurement_rfq_supplier_quotation'),
    sa.UniqueConstraint('tenant_id', 'quotation_number', name='uq_procurement_supplier_quotation_number')
    )
    op.create_index('ix_procurement_quotation_tenant_status', 'procurement_supplier_quotations', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_supplier_quotations_tenant_id'), 'procurement_supplier_quotations', ['tenant_id'], unique=False)
    op.create_table('procurement_supplier_quotation_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('rfq_line_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('offered_quantity', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_procurement_supplier_quotation_lines_quote_price_nonnegative')),
    sa.ForeignKeyConstraint(['quotation_id'], ['procurement_supplier_quotations.id'], name=op.f('fk_procurement_supplier_quotation_lines_quotation_id_procurement_supplier_quotations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rfq_line_id'], ['procurement_rfq_lines.id'], name=op.f('fk_procurement_supplier_quotation_lines_rfq_line_id_procurement_rfq_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_supplier_quotation_lines')),
    sa.UniqueConstraint('quotation_id', 'rfq_line_id', name='uq_procurement_quotation_rfq_line')
    )
    op.create_index(op.f('ix_procurement_supplier_quotation_lines_tenant_id'), 'procurement_supplier_quotation_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_supplier_quotation_lines_tenant_id'), table_name='procurement_supplier_quotation_lines')
    op.drop_table('procurement_supplier_quotation_lines')
    op.drop_index(op.f('ix_procurement_supplier_quotations_tenant_id'), table_name='procurement_supplier_quotations')
    op.drop_index('ix_procurement_quotation_tenant_status', table_name='procurement_supplier_quotations')
    op.drop_table('procurement_supplier_quotations')
    op.drop_index(op.f('ix_procurement_rfq_lines_tenant_id'), table_name='procurement_rfq_lines')
    op.drop_table('procurement_rfq_lines')
    op.drop_index(op.f('ix_procurement_rfqs_tenant_id'), table_name='procurement_rfqs')
    op.drop_index('ix_procurement_rfq_tenant_status', table_name='procurement_rfqs')
    op.drop_index('ix_procurement_rfq_tenant_closing', table_name='procurement_rfqs')
    op.drop_table('procurement_rfqs')

    sa.Enum(
        name='procurement_quotation_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_rfq_status',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
