"""add procurement approval workflow

Revision ID: 89a51add0860
Revises: c8df25360259
Create Date: 2026-08-09 10:15:32.206369
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '89a51add0860'
down_revision: Union[str, Sequence[str], None] = 'c8df25360259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.Enum('PURCHASE_REQUISITION', 'PURCHASE_ORDER', 'INVOICE_MATCH', 'SUPPLIER_RETURN', name='procurement_approval_object_type'), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'CANCELLED', name='procurement_approval_request_status'), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_approval_requests')),
    sa.UniqueConstraint('tenant_id', 'object_type', 'object_id', name='uq_proc_approval_object')
    )
    op.create_index('ix_proc_approval_tenant_object', 'procurement_approval_requests', ['tenant_id', 'object_type', 'object_id'], unique=False)
    op.create_index('ix_proc_approval_tenant_status', 'procurement_approval_requests', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_approval_requests_tenant_id'), 'procurement_approval_requests', ['tenant_id'], unique=False)
    op.create_table('procurement_approval_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SKIPPED', name='procurement_approval_step_status'), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('step_number > 0', name=op.f('ck_procurement_approval_steps_approval_step_number_positive')),
    sa.ForeignKeyConstraint(['approval_request_id'], ['procurement_approval_requests.id'], name=op.f('fk_proc_approval_step_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_approval_steps')),
    sa.UniqueConstraint('approval_request_id', 'step_number', name='uq_proc_approval_step_number')
    )
    op.create_index('ix_proc_approval_step_tenant_status', 'procurement_approval_steps', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_approval_steps_tenant_id'), 'procurement_approval_steps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_approval_steps_tenant_id'), table_name='procurement_approval_steps')
    op.drop_index('ix_proc_approval_step_tenant_status', table_name='procurement_approval_steps')
    op.drop_table('procurement_approval_steps')
    op.drop_index(op.f('ix_procurement_approval_requests_tenant_id'), table_name='procurement_approval_requests')
    op.drop_index('ix_proc_approval_tenant_status', table_name='procurement_approval_requests')
    op.drop_index('ix_proc_approval_tenant_object', table_name='procurement_approval_requests')
    op.drop_table('procurement_approval_requests')

    # APPROVAL_WORKFLOW_ENUM_CLEANUP
    sa.Enum(
        name='procurement_approval_step_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_approval_request_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_approval_object_type',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
