"""add supplier return domain

Revision ID: c8df25360259
Revises: e1ebc61ba257
Create Date: 2026-08-08 23:54:55.824225
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c8df25360259'
down_revision: Union[str, Sequence[str], None] = 'e1ebc61ba257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_supplier_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('invoice_match_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REQUESTED', 'AUTHORIZED', 'DISPATCHED', 'RECEIVED_BY_SUPPLIER', 'CREDIT_PENDING', 'SETTLED', 'REJECTED', 'CANCELLED', name='procurement_supplier_return_status'), nullable=False),
    sa.Column('claim_status', sa.Enum('NOT_REQUIRED', 'OPEN', 'ACKNOWLEDGED', 'DISPUTED', 'APPROVED', 'REJECTED', 'SETTLED', name='procurement_supplier_claim_status'), nullable=False),
    sa.Column('supplier_return_authorization', sa.String(length=150), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True, comment='Reference to Warehouse service.'),
    sa.Column('shipment_id', sa.UUID(), nullable=True, comment='Reference to Logistics/Fleet service.'),
    sa.Column('estimated_return_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('supplier_claim_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_credit_reference', sa.String(length=100), nullable=True),
    sa.Column('finance_ap_adjustment_id', sa.UUID(), nullable=True, comment='Reference to Finance/AP debit-credit adjustment created after return settlement.'),
    sa.Column('finance_handoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimated_return_value >= 0', name=op.f('ck_procurement_supplier_returns_return_value_nonneg')),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['procurement_goods_receipts.id'], name=op.f('fk_proc_return_goods_receipt'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_match_id'], ['procurement_supplier_invoice_matches.id'], name=op.f('fk_proc_return_invoice_match'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['procurement_purchase_orders.id'], name=op.f('fk_proc_return_purchase_order'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], name=op.f('fk_proc_return_supplier'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_supplier_returns')),
    sa.UniqueConstraint('tenant_id', 'return_number', name='uq_procurement_supplier_return_number')
    )
    op.create_index('ix_procurement_return_tenant_receipt', 'procurement_supplier_returns', ['tenant_id', 'goods_receipt_id'], unique=False)
    op.create_index('ix_procurement_return_tenant_status', 'procurement_supplier_returns', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_procurement_return_tenant_supplier', 'procurement_supplier_returns', ['tenant_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_procurement_supplier_returns_tenant_id'), 'procurement_supplier_returns', ['tenant_id'], unique=False)
    op.create_table('procurement_supplier_return_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_return_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_line_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True, comment='Reference to Inventory item master.'),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('return_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('line_value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('reason', sa.Enum('DAMAGED', 'QUALITY_FAILURE', 'WRONG_ITEM', 'EXCESS_QUANTITY', 'EXPIRED', 'SPECIFICATION_MISMATCH', 'RECALL', 'OTHER', name='procurement_supplier_return_reason'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'DISPATCHED', 'RECEIVED_BY_SUPPLIER', 'REJECTED', 'SETTLED', name='procurement_supplier_return_line_status'), nullable=False),
    sa.Column('inspection_reference', sa.String(length=150), nullable=True),
    sa.Column('quality_case_id', sa.UUID(), nullable=True, comment='Reference to Quality/Laboratory service.'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('line_value >= 0', name=op.f('ck_procurement_supplier_return_lines_return_line_value_nonneg')),
    sa.CheckConstraint('return_quantity > 0', name=op.f('ck_procurement_supplier_return_lines_return_line_qty_pos')),
    sa.CheckConstraint('unit_value >= 0', name=op.f('ck_procurement_supplier_return_lines_return_line_unit_nonneg')),
    sa.ForeignKeyConstraint(['goods_receipt_line_id'], ['procurement_goods_receipt_lines.id'], name=op.f('fk_proc_return_line_goods_receipt'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['procurement_purchase_order_lines.id'], name=op.f('fk_proc_return_line_po_line'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_return_id'], ['procurement_supplier_returns.id'], name=op.f('fk_proc_return_line_parent'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_supplier_return_lines')),
    sa.UniqueConstraint('supplier_return_id', 'line_number', name='uq_procurement_supplier_return_line_number')
    )
    op.create_index(op.f('ix_procurement_supplier_return_lines_tenant_id'), 'procurement_supplier_return_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_supplier_return_lines_tenant_id'), table_name='procurement_supplier_return_lines')
    op.drop_table('procurement_supplier_return_lines')
    op.drop_index(op.f('ix_procurement_supplier_returns_tenant_id'), table_name='procurement_supplier_returns')
    op.drop_index('ix_procurement_return_tenant_supplier', table_name='procurement_supplier_returns')
    op.drop_index('ix_procurement_return_tenant_status', table_name='procurement_supplier_returns')
    op.drop_index('ix_procurement_return_tenant_receipt', table_name='procurement_supplier_returns')
    op.drop_table('procurement_supplier_returns')

    # SUPPLIER_RETURN_ENUM_CLEANUP
    sa.Enum(
        name='procurement_supplier_return_line_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_supplier_return_reason',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_supplier_claim_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_supplier_return_status',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
