"""add supplier invoice matching domain

Revision ID: e1ebc61ba257
Revises: 090669936e69
Create Date: 2026-08-08 23:22:50.792980
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'e1ebc61ba257'
down_revision: Union[str, Sequence[str], None] = '090669936e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_supplier_invoice_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('invoice_subtotal', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('invoice_tax_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('invoice_total', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('quantity_tolerance_percent', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('price_tolerance_percent', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('tax_tolerance_percent', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'WITHIN_TOLERANCE', 'EXCEPTION', 'DISPUTED', 'APPROVED', 'REJECTED', 'HANDED_OFF', name='procurement_invoice_match_status'), nullable=False),
    sa.Column('exception_type', sa.Enum('NONE', 'PO_NOT_FOUND', 'RECEIPT_NOT_FOUND', 'QUANTITY_MISMATCH', 'PRICE_MISMATCH', 'TAX_MISMATCH', 'DUPLICATE_INVOICE', name='procurement_invoice_match_exception_type'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_ap_invoice_id', sa.UUID(), nullable=True, comment='Reference to Finance/AP invoice after successful procurement handoff.'),
    sa.Column('finance_handoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('invoice_subtotal >= 0', name=op.f('ck_procurement_supplier_invoice_matches_inv_subtotal_nonneg')),
    sa.CheckConstraint('invoice_tax_amount >= 0', name=op.f('ck_procurement_supplier_invoice_matches_match_tax_nonnegative')),
    sa.CheckConstraint('invoice_total >= 0', name=op.f('ck_procurement_supplier_invoice_matches_match_total_nonnegative')),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['procurement_goods_receipts.id'], name=op.f('fk_proc_inv_match_goods_receipt'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['procurement_purchase_orders.id'], name=op.f('fk_proc_inv_match_purchase_order'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement_suppliers.id'], name=op.f('fk_proc_inv_match_supplier'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_supplier_invoice_matches')),
    sa.UniqueConstraint('tenant_id', 'supplier_id', 'supplier_invoice_number', name='uq_procurement_invoice_match_supplier_invoice')
    )
    op.create_index('ix_procurement_match_tenant_po', 'procurement_supplier_invoice_matches', ['tenant_id', 'purchase_order_id'], unique=False)
    op.create_index('ix_procurement_match_tenant_status', 'procurement_supplier_invoice_matches', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_procurement_match_tenant_supplier', 'procurement_supplier_invoice_matches', ['tenant_id', 'supplier_id'], unique=False)
    op.create_index(op.f('ix_procurement_supplier_invoice_matches_tenant_id'), 'procurement_supplier_invoice_matches', ['tenant_id'], unique=False)
    op.create_table('procurement_supplier_invoice_match_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_match_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_line_id', sa.UUID(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True, comment='Reference to Inventory item master.'),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('invoiced_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('invoiced_unit_price', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('invoiced_tax_amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('invoiced_line_total', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('po_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('po_unit_price', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('quantity_variance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('price_variance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('tax_variance', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('status', sa.Enum('MATCHED', 'QUANTITY_VARIANCE', 'PRICE_VARIANCE', 'TAX_VARIANCE', 'MULTIPLE_VARIANCES', name='procurement_invoice_match_line_status'), nullable=False),
    sa.Column('exception_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('invoiced_line_total >= 0', name=op.f('ck_procurement_supplier_invoice_match_lines_inv_ln_total_nonneg')),
    sa.CheckConstraint('invoiced_quantity > 0', name=op.f('ck_procurement_supplier_invoice_match_lines_inv_line_qty_pos')),
    sa.CheckConstraint('invoiced_tax_amount >= 0', name=op.f('ck_procurement_supplier_invoice_match_lines_inv_line_tax_nonneg')),
    sa.CheckConstraint('invoiced_unit_price >= 0', name=op.f('ck_procurement_supplier_invoice_match_lines_inv_ln_price_nonneg')),
    sa.ForeignKeyConstraint(['goods_receipt_line_id'], ['procurement_goods_receipt_lines.id'], name=op.f('fk_proc_inv_match_line_goods_receipt'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_match_id'], ['procurement_supplier_invoice_matches.id'], name=op.f('fk_proc_inv_match_line_parent'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['procurement_purchase_order_lines.id'], name=op.f('fk_proc_inv_match_line_po_line'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_supplier_invoice_match_lines')),
    sa.UniqueConstraint('invoice_match_id', 'line_number', name='uq_procurement_invoice_match_line_number')
    )
    op.create_index(op.f('ix_procurement_supplier_invoice_match_lines_tenant_id'), 'procurement_supplier_invoice_match_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_supplier_invoice_match_lines_tenant_id'), table_name='procurement_supplier_invoice_match_lines')
    op.drop_table('procurement_supplier_invoice_match_lines')
    op.drop_index(op.f('ix_procurement_supplier_invoice_matches_tenant_id'), table_name='procurement_supplier_invoice_matches')
    op.drop_index('ix_procurement_match_tenant_supplier', table_name='procurement_supplier_invoice_matches')
    op.drop_index('ix_procurement_match_tenant_status', table_name='procurement_supplier_invoice_matches')
    op.drop_index('ix_procurement_match_tenant_po', table_name='procurement_supplier_invoice_matches')
    op.drop_table('procurement_supplier_invoice_matches')

    # INVOICE_MATCH_ENUM_CLEANUP
    sa.Enum(
        name='procurement_invoice_match_line_status',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_invoice_match_exception_type',
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name='procurement_invoice_match_status',
    ).drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
